<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre4 Chronologies | Explorer la Trans-Atlantic Slave trade Database avec R</title>
  <meta name="description" content="Chapitre4 Chronologies | Explorer la Trans-Atlantic Slave trade Database avec R" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre4 Chronologies | Explorer la Trans-Atlantic Slave trade Database avec R" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre4 Chronologies | Explorer la Trans-Atlantic Slave trade Database avec R" />
  
  
  

<meta name="author" content="Wilfrid Cariou" />


<meta name="date" content="2020-04-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="manipulations.html"/>
<link rel="next" href="cartographie.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Explorer la TASTDb avec R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="prise-en-main.html"><a href="prise-en-main.html"><i class="fa fa-check"></i><b>1</b> Prise en main</a><ul>
<li class="chapter" data-level="1.1" data-path="prise-en-main.html"><a href="prise-en-main.html#installation"><i class="fa fa-check"></i><b>1.1</b> Installation</a><ul>
<li class="chapter" data-level="1.1.1" data-path="prise-en-main.html"><a href="prise-en-main.html#installer-r"><i class="fa fa-check"></i><b>1.1.1</b> Installer R</a></li>
<li class="chapter" data-level="1.1.2" data-path="prise-en-main.html"><a href="prise-en-main.html#installer-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> Installer RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="prise-en-main.html"><a href="prise-en-main.html#evolutivité"><i class="fa fa-check"></i><b>1.2</b> Evolutivité</a></li>
<li class="chapter" data-level="1.3" data-path="prise-en-main.html"><a href="prise-en-main.html#interface"><i class="fa fa-check"></i><b>1.3</b> Interface</a><ul>
<li class="chapter" data-level="1.3.1" data-path="prise-en-main.html"><a href="prise-en-main.html#quelques-repères-indispensables-pour-débuter"><i class="fa fa-check"></i><b>1.3.1</b> Quelques repères indispensables pour débuter</a></li>
<li class="chapter" data-level="1.3.2" data-path="prise-en-main.html"><a href="prise-en-main.html#organiser-ses-fichiers-dans-un-projet"><i class="fa fa-check"></i><b>1.3.2</b> Organiser ses fichiers dans un projet</a></li>
<li class="chapter" data-level="1.3.3" data-path="prise-en-main.html"><a href="prise-en-main.html#console-et-scripts"><i class="fa fa-check"></i><b>1.3.3</b> Console et scripts</a><ul>
<li class="chapter" data-level="1.3.3.1" data-path="prise-en-main.html"><a href="prise-en-main.html#comment-saisir-une-instruction-dans-la-console"><i class="fa fa-check"></i><b>1.3.3.1</b> Comment saisir une instruction dans la console ?</a></li>
<li class="chapter" data-level="1.3.3.2" data-path="prise-en-main.html"><a href="prise-en-main.html#comment-saisir-une-instruction-dans-un-script"><i class="fa fa-check"></i><b>1.3.3.2</b> Comment saisir une instruction dans un script ?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="prise-en-main.html"><a href="prise-en-main.html#lecture-des-données"><i class="fa fa-check"></i><b>1.4</b> Lecture des données</a><ul>
<li class="chapter" data-level="1.4.1" data-path="prise-en-main.html"><a href="prise-en-main.html#packages"><i class="fa fa-check"></i><b>1.4.1</b> Packages</a></li>
<li class="chapter" data-level="1.4.2" data-path="prise-en-main.html"><a href="prise-en-main.html#importation-des-données"><i class="fa fa-check"></i><b>1.4.2</b> Importation des données</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="prise-en-main.html"><a href="prise-en-main.html#quelques-bases-du-langage"><i class="fa fa-check"></i><b>1.5</b> Quelques bases du langage</a><ul>
<li class="chapter" data-level="1.5.1" data-path="prise-en-main.html"><a href="prise-en-main.html#des-instructions-simples-les-expressions-arithmétiques"><i class="fa fa-check"></i><b>1.5.1</b> Des instructions simples, les expressions arithmétiques</a></li>
<li class="chapter" data-level="1.5.2" data-path="prise-en-main.html"><a href="prise-en-main.html#les-variables"><i class="fa fa-check"></i><b>1.5.2</b> Les variables</a><ul>
<li class="chapter" data-level="1.5.2.1" data-path="prise-en-main.html"><a href="prise-en-main.html#afficher-le-contenu-dune-variable"><i class="fa fa-check"></i><b>1.5.2.1</b> Afficher le contenu d’une variable</a></li>
<li class="chapter" data-level="1.5.2.2" data-path="prise-en-main.html"><a href="prise-en-main.html#supprimer-une-variable"><i class="fa fa-check"></i><b>1.5.2.2</b> Supprimer une variable</a></li>
<li class="chapter" data-level="1.5.2.3" data-path="prise-en-main.html"><a href="prise-en-main.html#réaffecter-une-valeur-à-une-variable"><i class="fa fa-check"></i><b>1.5.2.3</b> Réaffecter une valeur à une variable</a></li>
<li class="chapter" data-level="1.5.2.4" data-path="prise-en-main.html"><a href="prise-en-main.html#exemple-de-séquence-dinstructions"><i class="fa fa-check"></i><b>1.5.2.4</b> Exemple de séquence d’instructions</a></li>
</ul></li>
<li class="chapter" data-level="1.5.3" data-path="prise-en-main.html"><a href="prise-en-main.html#les-vecteurs"><i class="fa fa-check"></i><b>1.5.3</b> Les vecteurs</a></li>
<li class="chapter" data-level="1.5.4" data-path="prise-en-main.html"><a href="prise-en-main.html#les-fonctions"><i class="fa fa-check"></i><b>1.5.4</b> Les fonctions</a><ul>
<li class="chapter" data-level="1.5.4.1" data-path="prise-en-main.html"><a href="prise-en-main.html#découvrir-les-fonctions"><i class="fa fa-check"></i><b>1.5.4.1</b> Découvrir les fonctions</a></li>
<li class="chapter" data-level="1.5.4.2" data-path="prise-en-main.html"><a href="prise-en-main.html#découvrir-quelques-fonctions-existantes-de-r-base"><i class="fa fa-check"></i><b>1.5.4.2</b> Découvrir quelques fonctions existantes de R Base</a></li>
<li class="chapter" data-level="1.5.4.3" data-path="prise-en-main.html"><a href="prise-en-main.html#imbriquer-des-fonctions"><i class="fa fa-check"></i><b>1.5.4.3</b> Imbriquer des fonctions</a></li>
</ul></li>
<li class="chapter" data-level="1.5.5" data-path="prise-en-main.html"><a href="prise-en-main.html#règles-et-conventions-de-syntaxe"><i class="fa fa-check"></i><b>1.5.5</b> Règles et conventions de syntaxe</a><ul>
<li class="chapter" data-level="1.5.5.1" data-path="prise-en-main.html"><a href="prise-en-main.html#déclaration"><i class="fa fa-check"></i><b>1.5.5.1</b> Déclaration</a></li>
<li class="chapter" data-level="1.5.5.2" data-path="prise-en-main.html"><a href="prise-en-main.html#conventions-de-déclaration"><i class="fa fa-check"></i><b>1.5.5.2</b> Conventions de déclaration</a></li>
<li class="chapter" data-level="1.5.5.3" data-path="prise-en-main.html"><a href="prise-en-main.html#conventions-de-style"><i class="fa fa-check"></i><b>1.5.5.3</b> Conventions de style</a></li>
</ul></li>
<li class="chapter" data-level="1.5.6" data-path="prise-en-main.html"><a href="prise-en-main.html#commenter-ses-instructions"><i class="fa fa-check"></i><b>1.5.6</b> Commenter ses instructions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="inventaire.html"><a href="inventaire.html"><i class="fa fa-check"></i><b>2</b> Inventaire</a><ul>
<li class="chapter" data-level="2.1" data-path="inventaire.html"><a href="inventaire.html#inspection-visuelle-des-données"><i class="fa fa-check"></i><b>2.1</b> Inspection visuelle des données</a></li>
<li class="chapter" data-level="2.2" data-path="inventaire.html"><a href="inventaire.html#structure-des-données"><i class="fa fa-check"></i><b>2.2</b> Structure des données</a><ul>
<li class="chapter" data-level="2.2.1" data-path="inventaire.html"><a href="inventaire.html#voyages-un-objet-de-type-tibble"><i class="fa fa-check"></i><b>2.2.1</b> Voyages, un objet de type Tibble</a></li>
<li class="chapter" data-level="2.2.2" data-path="inventaire.html"><a href="inventaire.html#les-variables-1"><i class="fa fa-check"></i><b>2.2.2</b> Les variables</a><ul>
<li class="chapter" data-level="2.2.2.1" data-path="inventaire.html"><a href="inventaire.html#lister-les-en-têtes-variables-names"><i class="fa fa-check"></i><b>2.2.2.1</b> Lister les en-têtes (<em>variables names</em>)</a></li>
<li class="chapter" data-level="2.2.2.2" data-path="inventaire.html"><a href="inventaire.html#types-de-variables"><i class="fa fa-check"></i><b>2.2.2.2</b> Types de variables</a></li>
<li class="chapter" data-level="2.2.2.3" data-path="inventaire.html"><a href="inventaire.html#valeurs-disponibles-pour-chaque-variable"><i class="fa fa-check"></i><b>2.2.2.3</b> Valeurs disponibles pour chaque variable</a></li>
</ul></li>
<li class="chapter" data-level="2.2.3" data-path="inventaire.html"><a href="inventaire.html#visualiser-les-valeurs-uniques-dune-variable"><i class="fa fa-check"></i><b>2.2.3</b> Visualiser les valeurs uniques d’une variable</a></li>
<li class="chapter" data-level="2.2.4" data-path="inventaire.html"><a href="inventaire.html#dénombrer-le-nombre-de-valeurs-uniques-dune-variable"><i class="fa fa-check"></i><b>2.2.4</b> Dénombrer le nombre de valeurs uniques d’une variable</a></li>
<li class="chapter" data-level="2.2.5" data-path="inventaire.html"><a href="inventaire.html#dénombrer-le-nombre-de-na-dune-variable"><i class="fa fa-check"></i><b>2.2.5</b> Dénombrer le nombre de NA d’une variable</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="inventaire.html"><a href="inventaire.html#expéditions-ajoutées-à-lédition-2019-de-la-base-trans-atlantic-slave-trade-dabase"><i class="fa fa-check"></i><b>2.3</b> Expéditions ajoutées à l’édition 2019 de la base Trans Atlantic slave trade Dabase</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manipulations.html"><a href="manipulations.html"><i class="fa fa-check"></i><b>3</b> Manipulations</a><ul>
<li class="chapter" data-level="3.1" data-path="manipulations.html"><a href="manipulations.html#préalables"><i class="fa fa-check"></i><b>3.1</b> Préalables</a><ul>
<li class="chapter" data-level="3.1.1" data-path="manipulations.html"><a href="manipulations.html#tidyverse"><i class="fa fa-check"></i><b>3.1.1</b> Tidyverse</a></li>
<li class="chapter" data-level="3.1.2" data-path="manipulations.html"><a href="manipulations.html#appel-des-packages"><i class="fa fa-check"></i><b>3.1.2</b> Appel des packages</a></li>
<li class="chapter" data-level="3.1.3" data-path="manipulations.html"><a href="manipulations.html#mini-jeu-de-données-utilisé-comme-exemple"><i class="fa fa-check"></i><b>3.1.3</b> Mini-jeu de données utilisé comme exemple</a><ul>
<li class="chapter" data-level="3.1.3.1" data-path="manipulations.html"><a href="manipulations.html#visualisation-sou-la-forme-de-table-html"><i class="fa fa-check"></i><b>3.1.3.1</b> Visualisation sou la forme de table html</a></li>
<li class="chapter" data-level="3.1.3.2" data-path="manipulations.html"><a href="manipulations.html#visualisation-sou-la-forme-de-table-brute"><i class="fa fa-check"></i><b>3.1.3.2</b> Visualisation sou la forme de table brute</a></li>
</ul></li>
<li class="chapter" data-level="3.1.4" data-path="manipulations.html"><a href="manipulations.html#lopérateur-piping-operator"><i class="fa fa-check"></i><b>3.1.4</b> L’opérateur %&gt;% (piping operator)</a></li>
<li class="chapter" data-level="3.1.5" data-path="manipulations.html"><a href="manipulations.html#références"><i class="fa fa-check"></i><b>3.1.5</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="manipulations.html"><a href="manipulations.html#sélectionner-des-colonnes"><i class="fa fa-check"></i><b>3.2</b> Sélectionner des colonnes</a><ul>
<li class="chapter" data-level="3.2.1" data-path="manipulations.html"><a href="manipulations.html#opérations-courantes"><i class="fa fa-check"></i><b>3.2.1</b> Opérations courantes</a><ul>
<li class="chapter" data-level="3.2.1.1" data-path="manipulations.html"><a href="manipulations.html#sélection-dune-colonne-repérée-par-son-nom"><i class="fa fa-check"></i><b>3.2.1.1</b> Sélection d’une colonne repérée par son nom</a></li>
<li class="chapter" data-level="3.2.1.2" data-path="manipulations.html"><a href="manipulations.html#sélection-dune-colonne-repérée-par-sa-position-dindex"><i class="fa fa-check"></i><b>3.2.1.2</b> Sélection d’une colonne repérée par sa position d’index</a></li>
<li class="chapter" data-level="3.2.1.3" data-path="manipulations.html"><a href="manipulations.html#sélection-de-colonnes-multiples-noms-de-variables"><i class="fa fa-check"></i><b>3.2.1.3</b> Sélection de colonnes multiples (noms de variables)</a></li>
<li class="chapter" data-level="3.2.1.4" data-path="manipulations.html"><a href="manipulations.html#sélection-de-colonnes-multiples-position-dindex"><i class="fa fa-check"></i><b>3.2.1.4</b> Sélection de colonnes multiples (position d’index)</a></li>
<li class="chapter" data-level="3.2.1.5" data-path="manipulations.html"><a href="manipulations.html#sélection-de-colonnes-contiguës"><i class="fa fa-check"></i><b>3.2.1.5</b> Sélection de colonnes contiguës</a></li>
<li class="chapter" data-level="3.2.1.6" data-path="manipulations.html"><a href="manipulations.html#sélection-par-exclusion"><i class="fa fa-check"></i><b>3.2.1.6</b> Sélection par exclusion</a></li>
<li class="chapter" data-level="3.2.1.7" data-path="manipulations.html"><a href="manipulations.html#compléter-une-sélection-par-les-colonnes-non-encore-sélectionnées"><i class="fa fa-check"></i><b>3.2.1.7</b> Compléter une sélection par les colonnes non encore sélectionnées</a></li>
</ul></li>
<li class="chapter" data-level="3.2.2" data-path="manipulations.html"><a href="manipulations.html#opérations-particulières"><i class="fa fa-check"></i><b>3.2.2</b> Opérations particulières</a><ul>
<li class="chapter" data-level="3.2.2.1" data-path="manipulations.html"><a href="manipulations.html#ré-agencer-des-colonnes-alphabétiquement"><i class="fa fa-check"></i><b>3.2.2.1</b> Ré-agencer des colonnes alphabétiquement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="manipulations.html"><a href="manipulations.html#ordonner-les-lignes-en-fonction-des-colonnes"><i class="fa fa-check"></i><b>3.3</b> Ordonner les lignes en fonction des colonnes</a><ul>
<li class="chapter" data-level="3.3.1" data-path="manipulations.html"><a href="manipulations.html#tri-à-partir-dune-colonne-unique"><i class="fa fa-check"></i><b>3.3.1</b> Tri à partir d’une colonne unique</a><ul>
<li class="chapter" data-level="3.3.1.1" data-path="manipulations.html"><a href="manipulations.html#tri-ascendant"><i class="fa fa-check"></i><b>3.3.1.1</b> Tri ascendant</a></li>
<li class="chapter" data-level="3.3.1.2" data-path="manipulations.html"><a href="manipulations.html#tri-descendant"><i class="fa fa-check"></i><b>3.3.1.2</b> Tri descendant</a></li>
</ul></li>
<li class="chapter" data-level="3.3.2" data-path="manipulations.html"><a href="manipulations.html#tri-selon-plusieurs-colonnes"><i class="fa fa-check"></i><b>3.3.2</b> Tri selon plusieurs colonnes</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="manipulations.html"><a href="manipulations.html#filtrage-de-lignes"><i class="fa fa-check"></i><b>3.4</b> Filtrage de lignes</a><ul>
<li class="chapter" data-level="3.4.1" data-path="manipulations.html"><a href="manipulations.html#filtrage-en-fonction-dune-colonne"><i class="fa fa-check"></i><b>3.4.1</b> Filtrage en fonction d’une colonne</a><ul>
<li class="chapter" data-level="3.4.1.1" data-path="manipulations.html"><a href="manipulations.html#filtrage-portant-sur-des-données-textuelles"><i class="fa fa-check"></i><b>3.4.1.1</b> Filtrage portant sur des données textuelles</a></li>
<li class="chapter" data-level="3.4.1.2" data-path="manipulations.html"><a href="manipulations.html#filtrage-valeurs-numériques"><i class="fa fa-check"></i><b>3.4.1.2</b> Filtrage, valeurs numériques</a></li>
<li class="chapter" data-level="3.4.1.3" data-path="manipulations.html"><a href="manipulations.html#filtrage-basé-sur-un-vecteur"><i class="fa fa-check"></i><b>3.4.1.3</b> Filtrage basé sur un vecteur</a></li>
<li class="chapter" data-level="3.4.1.4" data-path="manipulations.html"><a href="manipulations.html#filtrage-des-observations-manquantes"><i class="fa fa-check"></i><b>3.4.1.4</b> Filtrage des observations manquantes</a></li>
</ul></li>
<li class="chapter" data-level="3.4.2" data-path="manipulations.html"><a href="manipulations.html#filtrage-en-fonction-de-plusieurs-colonnes"><i class="fa fa-check"></i><b>3.4.2</b> Filtrage en fonction de plusieurs colonnes</a><ul>
<li class="chapter" data-level="3.4.2.1" data-path="manipulations.html"><a href="manipulations.html#utilisation-de-la-fonction-filter"><i class="fa fa-check"></i><b>3.4.2.1</b> Utilisation de la fonction filter</a></li>
<li class="chapter" data-level="3.4.2.2" data-path="manipulations.html"><a href="manipulations.html#utilisation-de-la-fonction-filter_at"><i class="fa fa-check"></i><b>3.4.2.2</b> Utilisation de la fonction filter_at</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="manipulations.html"><a href="manipulations.html#exemples"><i class="fa fa-check"></i><b>3.5</b> Exemples</a><ul>
<li class="chapter" data-level="3.5.1" data-path="manipulations.html"><a href="manipulations.html#femmes-propriétaires-de-navires-nantais-armés-pour-la-traite-atlantique"><i class="fa fa-check"></i><b>3.5.1</b> Femmes propriétaires de navires nantais armés pour la traite atlantique</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chronologies.html"><a href="chronologies.html"><i class="fa fa-check"></i><b>4</b> Chronologies</a><ul>
<li class="chapter" data-level="4.1" data-path="chronologies.html"><a href="chronologies.html#préalables-1"><i class="fa fa-check"></i><b>4.1</b> Préalables</a><ul>
<li class="chapter" data-level="4.1.1" data-path="chronologies.html"><a href="chronologies.html#packages-1"><i class="fa fa-check"></i><b>4.1.1</b> Packages</a></li>
<li class="chapter" data-level="4.1.2" data-path="chronologies.html"><a href="chronologies.html#thème-personnalisé-gpglot2"><i class="fa fa-check"></i><b>4.1.2</b> Thème personnalisé gpglot2</a><ul>
<li class="chapter" data-level="4.1.2.1" data-path="chronologies.html"><a href="chronologies.html#tidyverse-1"><i class="fa fa-check"></i><b>4.1.2.1</b> Tidyverse</a></li>
<li class="chapter" data-level="4.1.2.2" data-path="chronologies.html"><a href="chronologies.html#autres-packages"><i class="fa fa-check"></i><b>4.1.2.2</b> Autres packages</a></li>
<li class="chapter" data-level="4.1.2.3" data-path="chronologies.html"><a href="chronologies.html#appel-des-packages-1"><i class="fa fa-check"></i><b>4.1.2.3</b> Appel des packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="chronologies.html"><a href="chronologies.html#chronologie-globale-de-la-traite"><i class="fa fa-check"></i><b>4.2</b> Chronologie globale de la traite</a><ul>
<li class="chapter" data-level="4.2.1" data-path="chronologies.html"><a href="chronologies.html#bornes-chronologiques-et-durée-de-la-traite"><i class="fa fa-check"></i><b>4.2.1</b> Bornes chronologiques et durée de la traite</a></li>
<li class="chapter" data-level="4.2.2" data-path="chronologies.html"><a href="chronologies.html#expéditions-de-traite"><i class="fa fa-check"></i><b>4.2.2</b> Expéditions de traite</a><ul>
<li class="chapter" data-level="4.2.2.1" data-path="chronologies.html"><a href="chronologies.html#tableau-deffectifs"><i class="fa fa-check"></i><b>4.2.2.1</b> Tableau d’effectifs</a></li>
<li class="chapter" data-level="4.2.2.2" data-path="chronologies.html"><a href="chronologies.html#nombre-moyen-dexpéditions-par-années"><i class="fa fa-check"></i><b>4.2.2.2</b> Nombre moyen d’expéditions par années</a></li>
<li class="chapter" data-level="4.2.2.3" data-path="chronologies.html"><a href="chronologies.html#dix-années-comportant-le-plus-grand-nombre-dexpéditions"><i class="fa fa-check"></i><b>4.2.2.3</b> Dix années comportant le plus grand nombre d’expéditions</a></li>
<li class="chapter" data-level="4.2.2.4" data-path="chronologies.html"><a href="chronologies.html#prise-en-considération-des-années-pour-lesquelles-des-mentions-dexpéditions-de-traite-sont-absentes."><i class="fa fa-check"></i><b>4.2.2.4</b> Prise en considération des années pour lesquelles des mentions d’expéditions de traite sont absentes.</a></li>
</ul></li>
<li class="chapter" data-level="4.2.3" data-path="chronologies.html"><a href="chronologies.html#esclaves-embarqués-par-années"><i class="fa fa-check"></i><b>4.2.3</b> Esclaves embarqués par années</a></li>
<li class="chapter" data-level="4.2.4" data-path="chronologies.html"><a href="chronologies.html#différentes-façons-de-mesurer-une-variation"><i class="fa fa-check"></i><b>4.2.4</b> Différentes façons de mesurer une variation</a><ul>
<li class="chapter" data-level="4.2.4.1" data-path="chronologies.html"><a href="chronologies.html#définitions"><i class="fa fa-check"></i><b>4.2.4.1</b> Définitions</a></li>
<li class="chapter" data-level="" data-path="chronologies.html"><a href="chronologies.html#variation-absolue"><i class="fa fa-check"></i>Variation absolue</a></li>
<li class="chapter" data-level="" data-path="chronologies.html"><a href="chronologies.html#le-pourcentage-dévolution-ou-taux-dévolution"><i class="fa fa-check"></i>Le pourcentage d’évolution ou taux d’évolution</a></li>
<li class="chapter" data-level="4.2.4.2" data-path="chronologies.html"><a href="chronologies.html#le-coefficient-multiplicateur"><i class="fa fa-check"></i><b>4.2.4.2</b> Le coefficient multiplicateur</a></li>
<li class="chapter" data-level="4.2.4.3" data-path="chronologies.html"><a href="chronologies.html#coefficient-multiplicateur-ou-taux-dévolution"><i class="fa fa-check"></i><b>4.2.4.3</b> Coefficient multiplicateur ou taux d’évolution ?</a></li>
</ul></li>
<li class="chapter" data-level="4.2.5" data-path="chronologies.html"><a href="chronologies.html#représentations-graphiques"><i class="fa fa-check"></i><b>4.2.5</b> Représentations graphiques</a><ul>
<li class="chapter" data-level="4.2.5.1" data-path="chronologies.html"><a href="chronologies.html#représentation-graphique-en-base-r"><i class="fa fa-check"></i><b>4.2.5.1</b> Représentation graphique en base R</a></li>
<li class="chapter" data-level="4.2.5.2" data-path="chronologies.html"><a href="chronologies.html#représentations-avancées-ggplot2"><i class="fa fa-check"></i><b>4.2.5.2</b> Représentations avancées (ggplot2)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chronologies.html"><a href="chronologies.html#chronologies-comparatives-de-la-traite"><i class="fa fa-check"></i><b>4.3</b> Chronologies comparatives de la traite</a><ul>
<li class="chapter" data-level="4.3.1" data-path="chronologies.html"><a href="chronologies.html#chronologie-des-expéditions-en-fonction-des-pavillons-de-navires"><i class="fa fa-check"></i><b>4.3.1</b> Chronologie des expéditions en fonction des pavillons de navires</a><ul>
<li class="chapter" data-level="4.3.1.1" data-path="chronologies.html"><a href="chronologies.html#tableaux"><i class="fa fa-check"></i><b>4.3.1.1</b> Tableaux</a></li>
<li class="chapter" data-level="4.3.1.2" data-path="chronologies.html"><a href="chronologies.html#représentations-graphiques-1"><i class="fa fa-check"></i><b>4.3.1.2</b> Représentations graphiques</a></li>
<li class="chapter" data-level="4.3.1.3" data-path="chronologies.html"><a href="chronologies.html#représentations-graphiques-avancées-ggplot2"><i class="fa fa-check"></i><b>4.3.1.3</b> Représentations graphiques avancées (ggplot2)</a></li>
<li class="chapter" data-level="4.3.1.4" data-path="chronologies.html"><a href="chronologies.html#chronologie-comparative-des-expéditions-de-traite-en-fonction-des-ports-de-départs"><i class="fa fa-check"></i><b>4.3.1.4</b> Chronologie comparative des expéditions de traite en fonction des ports de départs</a></li>
</ul></li>
<li class="chapter" data-level="4.3.2" data-path="chronologies.html"><a href="chronologies.html#chronologie-darrivée-des-navires-principaux-lieux-dachat-desclaves"><i class="fa fa-check"></i><b>4.3.2</b> Chronologie d’arrivée des navires, principaux lieux d’achat d’esclaves</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chronologies.html"><a href="chronologies.html#exemples-1"><i class="fa fa-check"></i><b>4.4</b> Exemples</a><ul>
<li class="chapter" data-level="4.4.1" data-path="chronologies.html"><a href="chronologies.html#chronologie-des-expéditions-de-traite-à-destination-de-saint-domingue"><i class="fa fa-check"></i><b>4.4.1</b> Chronologie des expéditions de traite à destination de Saint-Domingue</a><ul>
<li class="chapter" data-level="4.4.1.1" data-path="chronologies.html"><a href="chronologies.html#tableau-deffectifs-1"><i class="fa fa-check"></i><b>4.4.1.1</b> Tableau d’effectifs</a></li>
<li class="chapter" data-level="4.4.1.2" data-path="chronologies.html"><a href="chronologies.html#représentation-graphique"><i class="fa fa-check"></i><b>4.4.1.2</b> Représentation graphique</a></li>
</ul></li>
<li class="chapter" data-level="4.4.2" data-path="chronologies.html"><a href="chronologies.html#nombre-desclaves-embarqués-par-années-à-destination-de-saint-domingue"><i class="fa fa-check"></i><b>4.4.2</b> Nombre d’esclaves embarqués par années à destination de Saint-Domingue</a><ul>
<li class="chapter" data-level="4.4.2.1" data-path="chronologies.html"><a href="chronologies.html#tableau"><i class="fa fa-check"></i><b>4.4.2.1</b> Tableau</a></li>
<li class="chapter" data-level="4.4.2.2" data-path="chronologies.html"><a href="chronologies.html#représentation-graphique-1"><i class="fa fa-check"></i><b>4.4.2.2</b> Représentation graphique</a></li>
</ul></li>
<li class="chapter" data-level="4.4.3" data-path="chronologies.html"><a href="chronologies.html#chronologie-décennale-des-expéditions-de-traite-à-destination-de-saint-domingue-selon-les-ports-de-départ"><i class="fa fa-check"></i><b>4.4.3</b> Chronologie décennale des expéditions de traite à destination de Saint-Domingue selon les ports de départ</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cartographie.html"><a href="cartographie.html"><i class="fa fa-check"></i><b>5</b> Cartographie</a><ul>
<li class="chapter" data-level="5.1" data-path="cartographie.html"><a href="cartographie.html#préalables-2"><i class="fa fa-check"></i><b>5.1</b> Préalables</a><ul>
<li class="chapter" data-level="5.1.1" data-path="cartographie.html"><a href="cartographie.html#packages-2"><i class="fa fa-check"></i><b>5.1.1</b> Packages</a></li>
<li class="chapter" data-level="5.1.2" data-path="cartographie.html"><a href="cartographie.html#importation-des-données-1"><i class="fa fa-check"></i><b>5.1.2</b> Importation des données</a><ul>
<li class="chapter" data-level="5.1.2.1" data-path="cartographie.html"><a href="cartographie.html#fond-de-carte-statique-rattaché-au-package-tmap"><i class="fa fa-check"></i><b>5.1.2.1</b> Fond de carte statique rattaché au package tmap</a></li>
<li class="chapter" data-level="5.1.2.2" data-path="cartographie.html"><a href="cartographie.html#données-géoréférencées-des-bases-trans-atlantic-slave-et-inter-american-slave-trade"><i class="fa fa-check"></i><b>5.1.2.2</b> Données géoréférencées des bases Trans Atlantic slave et Inter American slave trade</a></li>
</ul></li>
<li class="chapter" data-level="5.1.3" data-path="cartographie.html"><a href="cartographie.html#références-1"><i class="fa fa-check"></i><b>5.1.3</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="cartographie.html"><a href="cartographie.html#lieux-de-la-traite"><i class="fa fa-check"></i><b>5.2</b> Lieux de la traite</a><ul>
<li class="chapter" data-level="5.2.1" data-path="cartographie.html"><a href="cartographie.html#tmap"><i class="fa fa-check"></i><b>5.2.1</b> tmap</a></li>
<li class="chapter" data-level="5.2.2" data-path="cartographie.html"><a href="cartographie.html#carte-statique"><i class="fa fa-check"></i><b>5.2.2</b> carte statique</a></li>
<li class="chapter" data-level="5.2.3" data-path="cartographie.html"><a href="cartographie.html#carte-interactive"><i class="fa fa-check"></i><b>5.2.3</b> carte interactive</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="cartographie.html"><a href="cartographie.html#cartes-basées-sur-un-filtrage"><i class="fa fa-check"></i><b>5.3</b> Cartes basées sur un filtrage</a><ul>
<li class="chapter" data-level="5.3.1" data-path="cartographie.html"><a href="cartographie.html#exemple-de-localisation-des-ports-négriers"><i class="fa fa-check"></i><b>5.3.1</b> Exemple de localisation des ports négriers</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="cartographie.html"><a href="cartographie.html#carte-des-lieux-dachat-des-esclaves-pour-nantes"><i class="fa fa-check"></i><b>5.4</b> Carte des Lieux d’achat des esclaves pour Nantes</a><ul>
<li class="chapter" data-level="5.4.1" data-path="cartographie.html"><a href="cartographie.html#carte-comparative-des-lieux-de-vente-en-fonction-pavillons"><i class="fa fa-check"></i><b>5.4.1</b> Carte comparative des lieux de vente en fonction pavillons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html"><i class="fa fa-check"></i><b>6</b> R intermédiaire</a><ul>
<li class="chapter" data-level="6.1" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html#fonctions-personnalisées"><i class="fa fa-check"></i><b>6.1</b> Fonctions personnalisées</a><ul>
<li class="chapter" data-level="6.1.1" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html#exemple-de-fonction-graphiques-chronologiques-de-ports-en-base-r"><i class="fa fa-check"></i><b>6.1.1</b> Exemple de fonction : graphiques chronologiques de ports en Base R</a></li>
<li class="chapter" data-level="6.1.2" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html#exemple-de-fonction-thème-graphique-ggplot2"><i class="fa fa-check"></i><b>6.1.2</b> Exemple de fonction : thème graphique (ggplot2)</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html#programmation"><i class="fa fa-check"></i><b>6.2</b> Programmation</a><ul>
<li class="chapter" data-level="6.2.1" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html#boucle-for"><i class="fa fa-check"></i><b>6.2.1</b> Boucle for</a><ul>
<li class="chapter" data-level="6.2.1.1" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html#exemples-2"><i class="fa fa-check"></i><b>6.2.1.1</b> Exemples</a></li>
<li class="chapter" data-level="6.2.1.2" data-path="r-intermédiaire.html"><a href="r-intermédiaire.html#cas-pratique-représentation-en-base-r-construite-à-partir-dune-boucle-for"><i class="fa fa-check"></i><b>6.2.1.2</b> Cas pratique : représentation en Base R construite à partir d’une boucle for</a></li>
</ul></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Explorer la Trans-Atlantic Slave trade Database avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chronologies" class="section level1">
<h1><span class="header-section-number">Chapitre4</span> Chronologies</h1>
<p>Une série temporelle ou chronologique (nous utiliserons les deux termes indifféremment) correspond à une série d’observations réalisées au cours du temps.</p>
<div id="préalables-1" class="section level2">
<h2><span class="header-section-number">4.1</span> Préalables</h2>
<div id="packages-1" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Packages</h3>
</div>
<div id="thème-personnalisé-gpglot2" class="section level3">
<h3><span class="header-section-number">4.1.2</span> Thème personnalisé gpglot2</h3>
<p>Les graphiques construits avec le package ggplot2 ont en commun un thème appelé <code>my_theme_chrono1</code> défini à l’aide d’une fonction.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="chronologies.html#cb1-1"></a>my_theme_chrono1 &lt;-<span class="st"> </span><span class="cf">function</span>() {<span class="kw">theme</span>(<span class="dt">plot.caption =</span><span class="kw">element_text</span>(<span class="dt">colour =</span>  <span class="st">&quot;grey25&quot;</span>),</span>
<span id="cb1-2"><a href="chronologies.html#cb1-2"></a>         <span class="dt">plot.subtitle =</span> <span class="kw">element_text</span>(<span class="dt">colour =</span> <span class="st">&quot;grey25&quot;</span>),</span>
<span id="cb1-3"><a href="chronologies.html#cb1-3"></a>         <span class="dt">axis.line.y =</span>  <span class="kw">element_blank</span>(), </span>
<span id="cb1-4"><a href="chronologies.html#cb1-4"></a>         <span class="dt">panel.background =</span> <span class="kw">element_blank</span>(), </span>
<span id="cb1-5"><a href="chronologies.html#cb1-5"></a>         <span class="dt">panel.grid.major.x =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb1-6"><a href="chronologies.html#cb1-6"></a>         <span class="dt">panel.grid.minor.x =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb1-7"><a href="chronologies.html#cb1-7"></a>         <span class="dt">panel.grid.minor.y =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb1-8"><a href="chronologies.html#cb1-8"></a>         <span class="dt">panel.grid.major.y =</span> <span class="kw">element_line</span>( <span class="dt">size=</span>.<span class="dv">1</span>, <span class="dt">color=</span><span class="st">&quot;grey&quot;</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>),</span>
<span id="cb1-9"><a href="chronologies.html#cb1-9"></a>         <span class="dt">axis.ticks.y =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb1-10"><a href="chronologies.html#cb1-10"></a>         <span class="dt">axis.text.y.left =</span> <span class="kw">element_text</span>(<span class="dt">vjust =</span> <span class="fl">-0.9</span>),</span>
<span id="cb1-11"><a href="chronologies.html#cb1-11"></a>         <span class="dt">axis.line.x =</span> <span class="kw">element_blank</span>())}</span></code></pre></div>
<div id="tidyverse-1" class="section level4">
<h4><span class="header-section-number">4.1.2.1</span> Tidyverse</h4>
<ul>
<li>dplyr : grammaire de manipulation des tableaux de données.</li>
<li>stringr : manipulation de chaînes de caractères.</li>
<li>ggplot2 :graphiques avancés.</li>
</ul>
</div>
<div id="autres-packages" class="section level4">
<h4><span class="header-section-number">4.1.2.2</span> Autres packages</h4>
<ul>
<li>ggpmisc, ggrepel, gganimate : extensions du package ggplot2.</li>
<li>zoo :package utilisée dans le calcul des moyennes mobiles.</li>
</ul>
</div>
<div id="appel-des-packages-1" class="section level4">
<h4><span class="header-section-number">4.1.2.3</span> Appel des packages</h4>
<p>La fonction <code>library</code> permet de charger un package et de rendre ses fonctionnalités disponibles. Elle doit être exécutée à chaque session.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="chronologies.html#cb2-1"></a><span class="kw">library</span>(tidyverse) </span>
<span id="cb2-2"><a href="chronologies.html#cb2-2"></a><span class="kw">library</span>(ggpmisc)</span>
<span id="cb2-3"><a href="chronologies.html#cb2-3"></a><span class="kw">library</span>(ggrepel)</span>
<span id="cb2-4"><a href="chronologies.html#cb2-4"></a><span class="kw">library</span>(gganimate)</span>
<span id="cb2-5"><a href="chronologies.html#cb2-5"></a><span class="kw">library</span>(zoo)</span></code></pre></div>
</div>
</div>
</div>
<div id="chronologie-globale-de-la-traite" class="section level2">
<h2><span class="header-section-number">4.2</span> Chronologie globale de la traite</h2>
<div id="bornes-chronologiques-et-durée-de-la-traite" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Bornes chronologiques et durée de la traite</h3>
<p>Vous pouvez obtenir des résumés des données par des instructions en base R ou par la fonction <code>summarise</code> du package dplyr. R base retourne les résultats sous la forme de valeurs contrairement à dplyr qui les retourne sous la forme d’un objet de type <em>data.frame</em>.</p>
<ul>
<li>Première mention d’une expédition (Base R)</li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="chronologies.html#cb3-1"></a><span class="kw">min</span>(voyages<span class="op">$</span>yearam) </span></code></pre></div>
<pre><code>## [1] 1514</code></pre>
<ul>
<li>Ultime mention d’une expédition (Base R)</li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="chronologies.html#cb5-1"></a><span class="kw">max</span>(voyages<span class="op">$</span>yearam)</span></code></pre></div>
<pre><code>## [1] 1866</code></pre>
<ul>
<li>Durée (étendue) (Base R)</li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="chronologies.html#cb7-1"></a><span class="kw">max</span>(voyages<span class="op">$</span>yearam)<span class="op">-</span><span class="kw">min</span>(voyages<span class="op">$</span>yearam) </span></code></pre></div>
<pre><code>## [1] 352</code></pre>
<ul>
<li>Package dplyr (package dplyr)</li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="chronologies.html#cb9-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb9-2"><a href="chronologies.html#cb9-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">date_max=</span><span class="kw">max</span>(yearam),</span>
<span id="cb9-3"><a href="chronologies.html#cb9-3"></a>            <span class="dt">date_min=</span><span class="kw">min</span>(yearam))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   date_max date_min
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1866     1514</code></pre>
</div>
<div id="expéditions-de-traite" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Expéditions de traite</h3>
<div id="tableau-deffectifs" class="section level4">
<h4><span class="header-section-number">4.2.2.1</span> Tableau d’effectifs</h4>
<p>Il s’agit de compter, pour chacune des valeurs de la variable <code>yearam</code>, le nombre d’observations ayant cette valeur. Ce « nombre de fois » s’appelle <em>l’effectif</em>. La construction d’un tableau d’effectifs appartient à la catégorie des opérations groupées dans Dplyr et s’effectue par le biais de la fonction <code>count</code>. La colonne d’effectifs est automatiquement appelée <code>n</code>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="chronologies.html#cb11-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb11-2"><a href="chronologies.html#cb11-2"></a><span class="st">  </span><span class="kw">count</span>(yearam)</span></code></pre></div>
<pre><code>## # A tibble: 335 x 2
##    yearam     n
##     &lt;dbl&gt; &lt;int&gt;
##  1   1514     1
##  2   1516     1
##  3   1520     1
##  4   1525     1
##  5   1526     5
##  6   1527     1
##  7   1532     5
##  8   1533     1
##  9   1534     2
## 10   1535     2
## # ... with 325 more rows</code></pre>
</div>
<div id="nombre-moyen-dexpéditions-par-années" class="section level4">
<h4><span class="header-section-number">4.2.2.2</span> Nombre moyen d’expéditions par années</h4>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="chronologies.html#cb13-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb13-2"><a href="chronologies.html#cb13-2"></a><span class="st">  </span><span class="kw">count</span>(yearam) <span class="op">%&gt;%</span></span>
<span id="cb13-3"><a href="chronologies.html#cb13-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">moyenne=</span><span class="kw">mean</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   moyenne
##     &lt;dbl&gt;
## 1    107.</code></pre>
</div>
<div id="dix-années-comportant-le-plus-grand-nombre-dexpéditions" class="section level4">
<h4><span class="header-section-number">4.2.2.3</span> Dix années comportant le plus grand nombre d’expéditions</h4>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="chronologies.html#cb15-1"></a> voyages <span class="op">%&gt;%</span></span>
<span id="cb15-2"><a href="chronologies.html#cb15-2"></a><span class="st">  </span><span class="kw">count</span>(yearam) <span class="op">%&gt;%</span></span>
<span id="cb15-3"><a href="chronologies.html#cb15-3"></a><span class="st">  </span><span class="kw">top_n</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>## Selecting by n</code></pre>
<pre><code>## # A tibble: 11 x 2
##    yearam     n
##     &lt;dbl&gt; &lt;int&gt;
##  1   1765   339
##  2   1766   354
##  3   1767   332
##  4   1770   332
##  5   1774   359
##  6   1790   345
##  7   1791   347
##  8   1792   360
##  9   1805   351
## 10   1806   371
## 11   1807   395</code></pre>
</div>
<div id="prise-en-considération-des-années-pour-lesquelles-des-mentions-dexpéditions-de-traite-sont-absentes." class="section level4">
<h4><span class="header-section-number">4.2.2.4</span> Prise en considération des années pour lesquelles des mentions d’expéditions de traite sont absentes.</h4>
<div id="tableau-chronologique-des-expéditions-de-traite" class="section level5">
<h5><span class="header-section-number">4.2.2.4.1</span> Tableau chronologique des expéditions de traite</h5>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chronologies.html#cb18-1"></a>n_exped &lt;-<span class="st">  </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb18-2"><a href="chronologies.html#cb18-2"></a><span class="st">  </span><span class="kw">count</span>(yearam)</span></code></pre></div>
</div>
<div id="tableau-chronologique-vide" class="section level5">
<h5><span class="header-section-number">4.2.2.4.2</span> Tableau chronologique “vide”</h5>
<p>On construit un vecteur de nombres entiers appelé <code>chrono</code>allant de 1514 à 1866. Ce vecteur est converti en tableau de données par la fonction <code>data.frame</code>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="chronologies.html#cb19-1"></a>chrono &lt;-<span class="st"> </span><span class="kw">data.frame</span> (<span class="dt">yearam =</span> <span class="kw">c</span>(<span class="dv">1514</span><span class="op">:</span><span class="dv">1866</span>)) </span></code></pre></div>
</div>
<div id="mise-en-relation-des-tables-n_exped-et-chrono" class="section level5">
<h5><span class="header-section-number">4.2.2.4.3</span> Mise en relation des tables “n_exped” et “chrono”</h5>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chronologies.html#cb20-1"></a>full_n_exped &lt;-<span class="st"> </span><span class="kw">left_join</span>(chrono, n_exped)</span></code></pre></div>
<pre><code>## Joining, by = &quot;yearam&quot;</code></pre>
<p>Cette combinaison des données de plusieurs tables est appelée jointure gauche.Elle conserve toutes les observations de la table <code>chrono</code>, même en l’absence de correspondances dans la table <code>n_exped</code> (et toutes les les colonnes des deux tables).<br />
Les lignes de <code>chrono</code>sans correspondance, c’est à dire pour lesquelles il n’existe pas d’expéditions de traite, prendront comme valeurs <code>na</code>dans la colonne <code>n</code> des effectifs.
S’il existe une correspondances, les effectifs d’expéditions seront reportés.
L’ordre des arguments de la fonction <code>left_join</code> a son importance. Comme on souhaite conserver la totalité des lignes de la table de gauche, cette dernière doit constituer le premier argument de la fonction, autrement-dit, celui situé à gauche.</p>
</div>
<div id="visualisation" class="section level5">
<h5><span class="header-section-number">4.2.2.4.4</span> Visualisation</h5>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="chronologies.html#cb22-1"></a><span class="kw">head</span>(full_n_exped, <span class="dv">20</span>)</span></code></pre></div>
<pre><code>##    yearam  n
## 1    1514  1
## 2    1515 NA
## 3    1516  1
## 4    1517 NA
## 5    1518 NA
## 6    1519 NA
## 7    1520  1
## 8    1521 NA
## 9    1522 NA
## 10   1523 NA
## 11   1524 NA
## 12   1525  1
## 13   1526  5
## 14   1527  1
## 15   1528 NA
## 16   1529 NA
## 17   1530 NA
## 18   1531 NA
## 19   1532  5
## 20   1533  1</code></pre>
</div>
</div>
</div>
<div id="esclaves-embarqués-par-années" class="section level3">
<h3><span class="header-section-number">4.2.3</span> Esclaves embarqués par années</h3>
<p>⚠️ Le résultat d’un calcul portant sur des termes incluant des valeurs manquantes est une valeur manquante.<br />
Vous pouvez calculer le nombre total d’esclaves embarqués par années à condition de prendre soin d’omettre les valeurs manquantes des termes du calcul.
Une rapide vérification par l’instruction ci-dessous révèle la présence de valeurs manquantes au sein de la variable <code>slaximp</code>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="chronologies.html#cb24-1"></a><span class="ot">NA</span> <span class="op">%in%</span><span class="st"> </span>voyages<span class="op">$</span>slaximp</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Prenons par exemple l’année 1653 qui comprend 10 expéditions pour lesquelles le nombre d’esclaves embarqués est partiellement connu.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="chronologies.html#cb26-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb26-2"><a href="chronologies.html#cb26-2"></a><span class="st">  </span><span class="kw">filter</span> (yearam <span class="op">==</span><span class="st"> </span><span class="dv">1653</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb26-3"><a href="chronologies.html#cb26-3"></a><span class="st">  </span><span class="kw">select</span>(shipname, yearam, slaximp) </span></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##    shipname                              yearam slaximp
##    &lt;chr&gt;                                  &lt;dbl&gt;   &lt;dbl&gt;
##  1 Gele Zon (a) Sol                        1653     340
##  2 Gele Engel (a) Engel Gabriel            1653     380
##  3 NS del Buen Sucesso y El Santo Cristo   1653     325
##  4 NS del Rosario y S Antonio              1653     325
##  5 S Maria                                 1653      NA
##  6 NS da Conceição e Penha da França       1653     381
##  7 Luipaard                                1653     273
##  8 Fortuijn                                1653     334
##  9 Blinde Fortuin                          1653     273
## 10 &lt;NA&gt;                                    1653     406</code></pre>
<p>Le résultat de l’addition du nombre d’esclaves embarqués par expédition pour l’année 1653 confirme que la présence de valeurs absentes parmi les termes d’une opération calculatoire retourne comme résultat <code>NA</code>.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chronologies.html#cb28-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb28-2"><a href="chronologies.html#cb28-2"></a><span class="st">  </span><span class="kw">filter</span> (yearam <span class="op">==</span><span class="st"> </span><span class="dv">1653</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb28-3"><a href="chronologies.html#cb28-3"></a><span class="st">  </span><span class="kw">select</span>(shipname, yearam, slaximp) <span class="op">%&gt;%</span></span>
<span id="cb28-4"><a href="chronologies.html#cb28-4"></a><span class="st">   </span><span class="kw">summarise</span> (<span class="dt">n_esc =</span> <span class="kw">sum</span>(slaximp))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   n_esc
##   &lt;dbl&gt;
## 1    NA</code></pre>
<p>Vous devez donc exclure les valeurs manquantes préalablement au calcul à effectuer. Deux syntaxes sont possibles.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="chronologies.html#cb30-1"></a><span class="co"># Syntaxe 1</span></span>
<span id="cb30-2"><a href="chronologies.html#cb30-2"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb30-3"><a href="chronologies.html#cb30-3"></a><span class="st">  </span><span class="kw">filter</span> (<span class="op">!</span><span class="kw">is.na</span>(slaximp)) <span class="op">%&gt;%</span></span>
<span id="cb30-4"><a href="chronologies.html#cb30-4"></a><span class="st">  </span><span class="kw">filter</span> (yearam <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1653</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb30-5"><a href="chronologies.html#cb30-5"></a><span class="st">  </span><span class="kw">group_by</span> (yearam) <span class="op">%&gt;%</span></span>
<span id="cb30-6"><a href="chronologies.html#cb30-6"></a><span class="st">  </span><span class="kw">summarise</span> (<span class="dt">n_esc =</span> <span class="kw">sum</span>(slaximp))</span></code></pre></div>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chronologies.html#cb31-1"></a><span class="co"># Syntaxe 2</span></span>
<span id="cb31-2"><a href="chronologies.html#cb31-2"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb31-3"><a href="chronologies.html#cb31-3"></a><span class="st">  </span><span class="kw">filter</span> (<span class="kw">complete.cases</span>(slaximp)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb31-4"><a href="chronologies.html#cb31-4"></a><span class="st">  </span><span class="kw">filter</span> (yearam <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1653</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb31-5"><a href="chronologies.html#cb31-5"></a><span class="st">  </span><span class="kw">group_by</span> (yearam) <span class="op">%&gt;%</span></span>
<span id="cb31-6"><a href="chronologies.html#cb31-6"></a><span class="st">  </span><span class="kw">summarise</span> (<span class="dt">n_esc =</span> <span class="kw">sum</span>(slaximp))</span></code></pre></div>
<pre><code>## # A tibble: 214 x 2
##    yearam n_esc
##     &lt;dbl&gt; &lt;dbl&gt;
##  1   1653  3037
##  2   1654  5488
##  3   1655  4270
##  4   1656  5675
##  5   1657  4596
##  6   1658  7037
##  7   1659  8184
##  8   1660  5549
##  9   1661  5157
## 10   1662  5290
## # ... with 204 more rows</code></pre>
</div>
<div id="différentes-façons-de-mesurer-une-variation" class="section level3">
<h3><span class="header-section-number">4.2.4</span> Différentes façons de mesurer une variation</h3>
<div id="définitions" class="section level4">
<h4><span class="header-section-number">4.2.4.1</span> Définitions</h4>
<p>On considère une quantité passant de la valeur initiale <span class="math inline">\(V1\)</span> à la valeur finale <span class="math inline">\(V2\)</span>.</p>
</div>
<div id="variation-absolue" class="section level4 unnumbered">
<h4>Variation absolue</h4>
<p>La variation absolue est la quantité <span class="math inline">\(V2–V1\)</span>.</p>
</div>
<div id="le-pourcentage-dévolution-ou-taux-dévolution" class="section level4 unnumbered">
<h4>Le pourcentage d’évolution ou taux d’évolution</h4>
<p>Le taux d’évolution est la variation relative exprimée en pourcentage. Ainsi on a : <span class="math inline">\(t\%=\frac{V2-V1}{V1}\times100\)</span></p>
<p>A retenir : la variation globale ne correspond pas à la somme de variations successives.</p>
</div>
<div id="le-coefficient-multiplicateur" class="section level4">
<h4><span class="header-section-number">4.2.4.2</span> Le coefficient multiplicateur</h4>
<ul>
<li>Le coefficient multiplicateur est le nombre par lequel il faut multiplier <span class="math inline">\(V1\)</span> pour obtenir <span class="math inline">\(V2\)</span>. On le note souvent <span class="math inline">\(CM\)</span>.
On a donc :<br />
<span class="math inline">\(V2=CM\times{V1}\)</span> ou encore <span class="math inline">\(CM=\frac{V2}{V1}\)</span></li>
</ul>
</div>
<div id="coefficient-multiplicateur-ou-taux-dévolution" class="section level4">
<h4><span class="header-section-number">4.2.4.3</span> Coefficient multiplicateur ou taux d’évolution ?</h4>
<ul>
<li>Lorsque la donnée à comparer est supérieure au double de l’autre on choisit généralement le coefficient multiplicateur.<br />
</li>
<li>Lorsque la donnée à comparer est inférieure au double de l’autre on choisit généralement le Taux de variation.</li>
</ul>
<div id="mise-en-pratique-évolutions-par-décennies" class="section level5">
<h5><span class="header-section-number">4.2.4.3.1</span> Mise en pratique : évolutions par décennies</h5>
<p>Le nombre d’expéditions est calculé par décennies par <code>count(year10)</code>. De nouvelles colonnes sont ajoutées au tableau d’effectifs par la fonction <code>mutate</code>. L’utilisateur en choisi le nom en veillant à respecter les conventions de r (noms en minuscules).
Pour mesurer une évolution entre deux valeurs, on utilise la fonction <code>lag</code> qui permet de faire référence à la valeur précédente.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="chronologies.html#cb33-1"></a>evolution &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb33-2"><a href="chronologies.html#cb33-2"></a><span class="st">  </span><span class="kw">count</span>(year10) <span class="op">%&gt;%</span></span>
<span id="cb33-3"><a href="chronologies.html#cb33-3"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">variation_absolue =</span> n<span class="op">-</span><span class="kw">lag</span>(n)) <span class="op">%&gt;%</span></span>
<span id="cb33-4"><a href="chronologies.html#cb33-4"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">taux_evolution =</span>  <span class="kw">paste</span>(<span class="kw">round</span>((n<span class="op">-</span><span class="kw">lag</span>(n))<span class="op">/</span><span class="kw">lag</span>(n)<span class="op">*</span><span class="dv">100</span>), <span class="st">&quot;%&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb33-5"><a href="chronologies.html#cb33-5"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">coeff_multiplicateur  =</span>  <span class="kw">round</span>(n<span class="op">/</span><span class="kw">lag</span>(n),<span class="dv">1</span>))</span></code></pre></div>
</div>
</div>
</div>
<div id="représentations-graphiques" class="section level3">
<h3><span class="header-section-number">4.2.5</span> Représentations graphiques</h3>
<div id="représentation-graphique-en-base-r" class="section level4">
<h4><span class="header-section-number">4.2.5.1</span> Représentation graphique en base R</h4>
<p>Vous pouvez “piper” la fonction <code>plot</code> après avoir compté le nombre d’observations par années. Le résultat obtenu est un graphique de type “nuage de points”.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="chronologies.html#cb34-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb34-2"><a href="chronologies.html#cb34-2"></a><span class="st">  </span><span class="kw">count</span>(yearam) <span class="op">%&gt;%</span></span>
<span id="cb34-3"><a href="chronologies.html#cb34-3"></a><span class="st">  </span><span class="kw">plot</span>()</span></code></pre></div>
<p><img src="RunH_files/figure-html/plot%20exp%20base%201-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Vous pouvez personnaliser le graphique par une géométrie de type marche d’escalier (<code>t="s"</code>) ou une courbe (<code>t="l"</code>) et le compléter par un habillage dont la taille des caractères est réglée par la fonction <code>cex</code>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="chronologies.html#cb35-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb35-2"><a href="chronologies.html#cb35-2"></a><span class="st">  </span><span class="kw">count</span>(yearam) <span class="op">%&gt;%</span></span>
<span id="cb35-3"><a href="chronologies.html#cb35-3"></a><span class="st">  </span><span class="kw">plot</span>(<span class="dt">t=</span><span class="st">&quot;s&quot;</span>,                                                         </span>
<span id="cb35-4"><a href="chronologies.html#cb35-4"></a>      <span class="dt">main=</span><span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb35-5"><a href="chronologies.html#cb35-5"></a>      <span class="dt">sub=</span><span class="st">&quot;Voyages, The TransAtlantic Salve Trade Db&quot;</span>,</span>
<span id="cb35-6"><a href="chronologies.html#cb35-6"></a>      <span class="dt">xlab=</span><span class="st">&quot;années&quot;</span>,</span>
<span id="cb35-7"><a href="chronologies.html#cb35-7"></a>      <span class="dt">ylab=</span><span class="st">&quot;expéditions&quot;</span>,</span>
<span id="cb35-8"><a href="chronologies.html#cb35-8"></a>      <span class="dt">cex.lab=</span><span class="fl">0.80</span>,</span>
<span id="cb35-9"><a href="chronologies.html#cb35-9"></a>      <span class="dt">cex.sub=</span><span class="fl">0.75</span>)</span></code></pre></div>
<p><img src="RunH_files/figure-html/plot%20exp%20base%202-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="représentations-avancées-ggplot2" class="section level4">
<h4><span class="header-section-number">4.2.5.2</span> Représentations avancées (ggplot2)</h4>
<div id="graphique-en-marche-descalier" class="section level5">
<h5><span class="header-section-number">4.2.5.2.1</span> Graphique en marche d’escalier</h5>
<p>Vous pouvez utiliser le package ggplot2 pour régler les intervalles des axes continus (fonction <code>scale_x_continuous</code>) et modifier l’apparence du graphique à l’aide d’un bibliothèque de thèmes ou en employant la fonction .<code>theme</code> pour des paramétrages manuels.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="chronologies.html#cb36-1"></a>n_exped &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb36-2"><a href="chronologies.html#cb36-2"></a><span class="st">  </span><span class="kw">count</span>(yearam)</span>
<span id="cb36-3"><a href="chronologies.html#cb36-3"></a></span>
<span id="cb36-4"><a href="chronologies.html#cb36-4"></a>gg_chrono1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(n_exped, <span class="kw">aes</span>(<span class="dt">x=</span> yearam, <span class="dt">y=</span> n))</span>
<span id="cb36-5"><a href="chronologies.html#cb36-5"></a>gg_chrono1 <span class="op">+</span></span>
<span id="cb36-6"><a href="chronologies.html#cb36-6"></a><span class="st">  </span><span class="kw">geom_area</span> (<span class="dt">color=</span><span class="st">&quot;#d95f02&quot;</span>, <span class="dt">fill=</span> <span class="kw">alpha</span>(<span class="st">&quot;#d95f02&quot;</span>, <span class="fl">0.1</span>)) <span class="op">+</span></span>
<span id="cb36-7"><a href="chronologies.html#cb36-7"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">1500</span>, <span class="dv">1875</span>, <span class="dt">by=</span><span class="dv">25</span>)) <span class="op">+</span></span>
<span id="cb36-8"><a href="chronologies.html#cb36-8"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">linetype=</span><span class="st">&quot;solid&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span></span>
<span id="cb36-9"><a href="chronologies.html#cb36-9"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb36-10"><a href="chronologies.html#cb36-10"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Expéditions&quot;</span>,</span>
<span id="cb36-11"><a href="chronologies.html#cb36-11"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019).Variable yearam</span></span>
<span id="cb36-12"><a href="chronologies.html#cb36-12"></a><span class="st">       </span><span class="ch">\n</span><span class="st"> W. Cariou (2020)&quot;</span>, <span class="dt">x=</span><span class="st">&quot;&quot;</span>,</span>
<span id="cb36-13"><a href="chronologies.html#cb36-13"></a>       <span class="dt">y=</span><span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb36-14"><a href="chronologies.html#cb36-14"></a><span class="st">   </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb36-15"><a href="chronologies.html#cb36-15"></a><span class="st">   </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">10</span>,<span class="dv">450</span>), <span class="dt">expand =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) </span></code></pre></div>
<p><img src="RunH_files/figure-html/ggplot2%20chrono%20exped%20escalier-1.svg" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="dégager-les-principales-variations" class="section level5">
<h5><span class="header-section-number">4.2.5.2.2</span> Dégager les principales variations</h5>
<p>Vous pouvez mettre en évidences les principaux pics (<code>stat_peaks</code>) et vallées (<code>stat_valleys</code>) par des symboles (argument <code>shape</code>) et les années correspondantes <code>text_repel</code>) en employant le package complémentaire à ggplot2, ggpmisc. Les arguments <code>ignore_threshold</code> et <code>span</code> permettant de sélectionner les variations les plus significatives. Le chevauchement des étiquettes est réglé par l’argument <code>geom ="text_repel"</code> en lien avec le package ggrepel.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="chronologies.html#cb37-1"></a><span class="kw">library</span>(ggpmisc)</span>
<span id="cb37-2"><a href="chronologies.html#cb37-2"></a><span class="kw">library</span>(ggrepel)</span>
<span id="cb37-3"><a href="chronologies.html#cb37-3"></a></span>
<span id="cb37-4"><a href="chronologies.html#cb37-4"></a>n_exped_pics_vallees &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb37-5"><a href="chronologies.html#cb37-5"></a><span class="st">  </span><span class="kw">count</span>(yearam)</span>
<span id="cb37-6"><a href="chronologies.html#cb37-6"></a></span>
<span id="cb37-7"><a href="chronologies.html#cb37-7"></a>gg_chrono1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(n_exped_pics_vallees , <span class="kw">aes</span>(<span class="dt">x=</span> yearam, <span class="dt">y=</span> n))</span>
<span id="cb37-8"><a href="chronologies.html#cb37-8"></a>gg_chrono1 <span class="op">+</span></span>
<span id="cb37-9"><a href="chronologies.html#cb37-9"></a><span class="st">    </span><span class="kw">geom_area</span> (<span class="dt">color=</span><span class="st">&quot;#d95f02&quot;</span>, <span class="dt">fill=</span> <span class="kw">alpha</span>(<span class="st">&quot;#d95f02&quot;</span>, <span class="fl">0.1</span>)) <span class="op">+</span></span>
<span id="cb37-10"><a href="chronologies.html#cb37-10"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">1500</span>, <span class="dv">1875</span>, <span class="dt">by =</span> <span class="dv">25</span>)) <span class="op">+</span></span>
<span id="cb37-11"><a href="chronologies.html#cb37-11"></a><span class="st">  </span><span class="kw">stat_peaks</span>(<span class="dt">ignore_threshold =</span> <span class="fl">0.4</span>, <span class="dt">colour =</span> <span class="st">&quot;#d95f02&quot;</span>, <span class="dt">span =</span><span class="dv">15</span>, <span class="dt">segment.colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">shape =</span> <span class="dv">2</span>) <span class="op">+</span></span>
<span id="cb37-12"><a href="chronologies.html#cb37-12"></a><span class="st">  </span><span class="kw">stat_peaks</span>(<span class="dt">ignore_threshold =</span> <span class="fl">0.4</span>, <span class="dt">colour =</span> <span class="st">&quot;#d95f02&quot;</span>, <span class="dt">span =</span><span class="dv">15</span>, <span class="dt">geom =</span><span class="st">&quot;text_repel&quot;</span>, <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">fontface=</span><span class="st">&quot;bold&quot;</span>) <span class="op">+</span></span>
<span id="cb37-13"><a href="chronologies.html#cb37-13"></a><span class="st">    </span><span class="kw">stat_valleys</span>(<span class="dt">ignore_threshold =</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.1</span>, <span class="dt">colour =</span> <span class="st">&quot;#1b9e77&quot;</span>, <span class="dt">span =</span> <span class="dv">15</span>, <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">shape=</span><span class="dv">6</span>) <span class="op">+</span></span>
<span id="cb37-14"><a href="chronologies.html#cb37-14"></a><span class="st">  </span><span class="kw">stat_valleys</span>(<span class="dt">ignore_threshold =</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.1</span>, <span class="dt">colour =</span> <span class="st">&quot;#1b9e77&quot;</span>, <span class="dt">span =</span> <span class="dv">15</span>, <span class="dt">geom =</span><span class="st">&quot;text_repel&quot;</span>, <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">fontface=</span><span class="st">&quot;bold&quot;</span>) <span class="op">+</span></span>
<span id="cb37-15"><a href="chronologies.html#cb37-15"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb37-16"><a href="chronologies.html#cb37-16"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Expéditions&quot;</span>,</span>
<span id="cb37-17"><a href="chronologies.html#cb37-17"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019).Variable yearam</span></span>
<span id="cb37-18"><a href="chronologies.html#cb37-18"></a><span class="st">       </span><span class="ch">\n</span><span class="st"> W. Cariou (2020)&quot;</span>, <span class="dt">x=</span><span class="st">&quot;&quot;</span>,</span>
<span id="cb37-19"><a href="chronologies.html#cb37-19"></a>       <span class="dt">y=</span><span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb37-20"><a href="chronologies.html#cb37-20"></a><span class="st">   </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb37-21"><a href="chronologies.html#cb37-21"></a><span class="st">   </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">10</span>,<span class="dv">450</span>), <span class="dt">expand =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="op">+</span></span>
<span id="cb37-22"><a href="chronologies.html#cb37-22"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">linetype=</span><span class="st">&quot;solid&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>)</span></code></pre></div>
<p><img src="RunH_files/figure-html/ggplot2 chrono exped pics-vallées-1.svg" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="dégager-une-tendance-par-lissage-par-moyenne-mobile" class="section level5">
<h5><span class="header-section-number">4.2.5.2.3</span> Dégager une tendance par lissage par moyenne mobile</h5>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="chronologies.html#cb38-1"></a>n_exped &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb38-2"><a href="chronologies.html#cb38-2"></a><span class="st">  </span><span class="kw">count</span>(yearam)</span>
<span id="cb38-3"><a href="chronologies.html#cb38-3"></a></span>
<span id="cb38-4"><a href="chronologies.html#cb38-4"></a></span>
<span id="cb38-5"><a href="chronologies.html#cb38-5"></a>gg_chrono1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(n_exped, <span class="kw">aes</span>(<span class="dt">x=</span> yearam, <span class="dt">y=</span> n))</span>
<span id="cb38-6"><a href="chronologies.html#cb38-6"></a>gg_chrono1 <span class="op">+</span></span>
<span id="cb38-7"><a href="chronologies.html#cb38-7"></a><span class="st">         </span><span class="kw">geom_area</span> (<span class="dt">color=</span><span class="st">&quot;#d95f02&quot;</span>, <span class="dt">fill=</span> <span class="kw">alpha</span>(<span class="st">&quot;#d95f02&quot;</span>, <span class="fl">0.1</span>)) <span class="op">+</span></span>
<span id="cb38-8"><a href="chronologies.html#cb38-8"></a><span class="st">       </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y=</span><span class="kw">rollmean</span>(n, <span class="dv">25</span>, <span class="dt">na.pad=</span><span class="ot">TRUE</span>)), <span class="dt">color=</span><span class="st">&quot;#1b9e77&quot;</span>, <span class="dt">size=</span><span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb38-9"><a href="chronologies.html#cb38-9"></a><span class="st">       </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">y=</span><span class="kw">rollmean</span>(n, <span class="dv">25</span>, <span class="dt">na.pad=</span><span class="ot">TRUE</span>)), <span class="dt">fill=</span><span class="st">&quot;#1b9e77&quot;</span>, <span class="dt">size=</span><span class="dv">1</span>, <span class="dt">alpha=</span>.<span class="dv">25</span>) <span class="op">+</span></span>
<span id="cb38-10"><a href="chronologies.html#cb38-10"></a><span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">1500</span>, <span class="dv">1875</span>, <span class="dt">by=</span><span class="dv">25</span>)) <span class="op">+</span></span>
<span id="cb38-11"><a href="chronologies.html#cb38-11"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb38-12"><a href="chronologies.html#cb38-12"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Expéditions, moyenne mobile centrée  fenêtre de 25 ans&quot;</span>,</span>
<span id="cb38-13"><a href="chronologies.html#cb38-13"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019).Variable yearam</span></span>
<span id="cb38-14"><a href="chronologies.html#cb38-14"></a><span class="st">       </span><span class="ch">\n</span><span class="st"> W. Cariou (2020)&quot;</span>, <span class="dt">x=</span><span class="st">&quot;&quot;</span>,</span>
<span id="cb38-15"><a href="chronologies.html#cb38-15"></a>       <span class="dt">y=</span><span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb38-16"><a href="chronologies.html#cb38-16"></a><span class="st">   </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb38-17"><a href="chronologies.html#cb38-17"></a><span class="st">   </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">10</span>,<span class="dv">450</span>), <span class="dt">expand =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="op">+</span></span>
<span id="cb38-18"><a href="chronologies.html#cb38-18"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">linetype=</span><span class="st">&quot;solid&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 24 rows containing missing values (position_stack).</code></pre>
<pre><code>## Warning: Removed 24 row(s) containing missing values (geom_path).</code></pre>
<p><img src="RunH_files/figure-html/ggplot2%20chrono%20exped%20moyenne%20mobile-1.svg" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="tendance-et-variabilité-par-boîtes-à-moustaches" class="section level5">
<h5><span class="header-section-number">4.2.5.2.4</span> Tendance et variabilité par boîtes à moustaches</h5>
<p>Vous pouvez résumer la distribution des expéditions par années regroupées en périodes par des boîte et moustache. Ce graphique trace une boîte autour du premier et troisième quartile. La médiane est figurée par le trait à l’intérieur de la boite et des moustaches sont tracées au-dessus et au-dessous de la case pour résumer l’étendue générale des observations. La boite à moustaches est dite “élaguée” car les moustaches ne correspond pas aux valeurs minimales et maximales de la série statistique. Des points sont dessinés pour les valeurs aberrantes en dehors des moustaches.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="chronologies.html#cb41-1"></a>n_exped25 &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb41-2"><a href="chronologies.html#cb41-2"></a><span class="st">  </span><span class="kw">count</span>(yearam, year25) <span class="op">%&gt;%</span></span>
<span id="cb41-3"><a href="chronologies.html#cb41-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year25 =</span> <span class="kw">sub</span>(<span class="st">&quot;years&quot;</span>, <span class="st">&quot;&quot;</span>, year25))</span>
<span id="cb41-4"><a href="chronologies.html#cb41-4"></a></span>
<span id="cb41-5"><a href="chronologies.html#cb41-5"></a>gg_chrono1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(n_exped25, <span class="kw">aes</span>(<span class="dt">x=</span> year25, <span class="dt">y =</span> n))</span>
<span id="cb41-6"><a href="chronologies.html#cb41-6"></a>gg_chrono1 <span class="op">+</span></span>
<span id="cb41-7"><a href="chronologies.html#cb41-7"></a><span class="st">   </span><span class="kw">geom_boxplot</span>(<span class="dt">colour =</span> <span class="st">&quot;#1b9e77&quot;</span>, <span class="dt">outlier.colour =</span> <span class="st">&quot;#d95f02&quot;</span>, <span class="dt">fill=</span> <span class="kw">alpha</span>(<span class="st">&quot;#1b9e77&quot;</span>, <span class="fl">0.3</span>)) <span class="op">+</span></span>
<span id="cb41-8"><a href="chronologies.html#cb41-8"></a><span class="st">   </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique par intervalles de 25 ans&quot;</span>,</span>
<span id="cb41-9"><a href="chronologies.html#cb41-9"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Distribution des expéditions par années pour chaque intervalle&quot;</span>,</span>
<span id="cb41-10"><a href="chronologies.html#cb41-10"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019).Variable yearam</span></span>
<span id="cb41-11"><a href="chronologies.html#cb41-11"></a><span class="st">       </span><span class="ch">\n</span><span class="st"> W. Cariou (2020)&quot;</span>, <span class="dt">x=</span><span class="st">&quot;&quot;</span>,</span>
<span id="cb41-12"><a href="chronologies.html#cb41-12"></a>       <span class="dt">y=</span><span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb41-13"><a href="chronologies.html#cb41-13"></a><span class="st">   </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb41-14"><a href="chronologies.html#cb41-14"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">linetype=</span><span class="st">&quot;solid&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span></span>
<span id="cb41-15"><a href="chronologies.html#cb41-15"></a><span class="st">   </span><span class="kw">scale_x_discrete</span>(<span class="dt">guide =</span> <span class="kw">guide_axis</span>(<span class="dt">n.dodge =</span> <span class="dv">2</span>))</span></code></pre></div>
<p><img src="RunH_files/figure-html/ggplot2%20chrono%20exped%20svg-1.svg" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
</div>
<div id="chronologies-comparatives-de-la-traite" class="section level2">
<h2><span class="header-section-number">4.3</span> Chronologies comparatives de la traite</h2>
<div id="chronologie-des-expéditions-en-fonction-des-pavillons-de-navires" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Chronologie des expéditions en fonction des pavillons de navires</h3>
<div id="tableaux" class="section level4">
<h4><span class="header-section-number">4.3.1.1</span> Tableaux</h4>
<div id="tableau-long" class="section level5">
<h5><span class="header-section-number">4.3.1.1.1</span> Tableau long</h5>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="chronologies.html#cb42-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb42-2"><a href="chronologies.html#cb42-2"></a><span class="st">  </span><span class="kw">count</span>(yearam, natinimp)</span></code></pre></div>
<pre><code>## # A tibble: 1,386 x 3
##    yearam natinimp              n
##     &lt;dbl&gt; &lt;chr&gt;             &lt;int&gt;
##  1   1514 Portugal / Brazil     1
##  2   1516 Portugal / Brazil     1
##  3   1520 &lt;NA&gt;                  1
##  4   1525 Portugal / Brazil     1
##  5   1526 Portugal / Brazil     1
##  6   1526 Spain / Uruguay       2
##  7   1526 &lt;NA&gt;                  2
##  8   1527 Spain / Uruguay       1
##  9   1532 Portugal / Brazil     3
## 10   1532 Spain / Uruguay       1
## # ... with 1,376 more rows</code></pre>
</div>
<div id="tableau-large-à-double-entrées" class="section level5">
<h5><span class="header-section-number">4.3.1.1.2</span> Tableau large (à double-entrées)</h5>
<p>La fonction <code>pivot_wider</code> du package <code>tidyr</code>(cf. tidyverse) vous permet de transformer des lignes en colonnes et ainsi passer d’un format de tableau long à un format large, où les nationalités deviennent des colonnes. <code>names_from</code> indique la colonne contenant les noms des nouvelles variables à créer et <code>values_from</code> indique la colonne contenant les valeurs de ces variables.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="chronologies.html#cb44-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb44-2"><a href="chronologies.html#cb44-2"></a><span class="st">  </span><span class="kw">count</span>(yearam, natinimp) <span class="op">%&gt;%</span></span>
<span id="cb44-3"><a href="chronologies.html#cb44-3"></a><span class="st">   </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> natinimp, <span class="dt">values_from =</span> n) </span></code></pre></div>
<pre><code>## # A tibble: 335 x 11
##    yearam `Portugal / Bra~  `NA` `Spain / Urugua~ `Great Britain` France
##     &lt;dbl&gt;            &lt;int&gt; &lt;int&gt;            &lt;int&gt;           &lt;int&gt;  &lt;int&gt;
##  1   1514                1    NA               NA              NA     NA
##  2   1516                1    NA               NA              NA     NA
##  3   1520               NA     1               NA              NA     NA
##  4   1525                1    NA               NA              NA     NA
##  5   1526                1     2                2              NA     NA
##  6   1527               NA    NA                1              NA     NA
##  7   1532                3     1                1              NA     NA
##  8   1533               NA     1               NA              NA     NA
##  9   1534                2    NA               NA              NA     NA
## 10   1535                2    NA               NA              NA     NA
## # ... with 325 more rows, and 5 more variables: Netherlands &lt;int&gt;, `Denmark /
## #   Baltic` &lt;int&gt;, USA &lt;int&gt;, Other &lt;int&gt;, Portugal &lt;int&gt;</code></pre>
</div>
</div>
<div id="représentations-graphiques-1" class="section level4">
<h4><span class="header-section-number">4.3.1.2</span> Représentations graphiques</h4>
</div>
<div id="représentations-graphiques-avancées-ggplot2" class="section level4">
<h4><span class="header-section-number">4.3.1.3</span> Représentations graphiques avancées (ggplot2)</h4>
<div id="graphiques-juxtaposés-échelle-arithmétique" class="section level5">
<h5><span class="header-section-number">4.3.1.3.1</span> Graphiques juxtaposés, échelle arithmétique</h5>
<p>La fonction <code>facet</code> du package ggplot2 partitionne un graphique en une matrice de panneaux en fonction de valeurs à l’instar d’un boucle.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="chronologies.html#cb46-1"></a><span class="co"># Préparation des données </span></span>
<span id="cb46-2"><a href="chronologies.html#cb46-2"></a>flagsyears_a &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb46-3"><a href="chronologies.html#cb46-3"></a><span class="st">  </span><span class="kw">count</span>(yearam, natinimp) <span class="op">%&gt;%</span></span>
<span id="cb46-4"><a href="chronologies.html#cb46-4"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(natinimp)) <span class="op">%&gt;%</span></span>
<span id="cb46-5"><a href="chronologies.html#cb46-5"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span>natinimp <span class="op">==</span><span class="st">&quot;Other&quot;</span>)</span>
<span id="cb46-6"><a href="chronologies.html#cb46-6"></a></span>
<span id="cb46-7"><a href="chronologies.html#cb46-7"></a></span>
<span id="cb46-8"><a href="chronologies.html#cb46-8"></a><span class="co"># facet </span></span>
<span id="cb46-9"><a href="chronologies.html#cb46-9"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb46-10"><a href="chronologies.html#cb46-10"></a>facet_flags &lt;-<span class="st"> </span><span class="kw">ggplot</span> (flagsyears_a, <span class="kw">aes</span>(<span class="dt">x=</span>yearam, <span class="dt">y=</span>n)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb46-11"><a href="chronologies.html#cb46-11"></a><span class="kw">geom_step</span> (<span class="dt">color=</span><span class="st">&quot;#d95f02&quot;</span>) <span class="op">+</span></span>
<span id="cb46-12"><a href="chronologies.html#cb46-12"></a><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">1500</span>, <span class="dv">1875</span>, <span class="dt">by=</span><span class="dv">50</span>)) <span class="op">+</span></span>
<span id="cb46-13"><a href="chronologies.html#cb46-13"></a><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb46-14"><a href="chronologies.html#cb46-14"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Pavillons&quot;</span>,</span>
<span id="cb46-15"><a href="chronologies.html#cb46-15"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019) variable yearam&quot;</span>,</span>
<span id="cb46-16"><a href="chronologies.html#cb46-16"></a>       <span class="dt">x=</span><span class="st">&quot;&quot;</span>, <span class="dt">y=</span><span class="st">&quot;expéditions&quot;</span>) <span class="op">+</span></span>
<span id="cb46-17"><a href="chronologies.html#cb46-17"></a><span class="st">       </span><span class="kw">my_theme_chrono1</span>() </span>
<span id="cb46-18"><a href="chronologies.html#cb46-18"></a>  </span>
<span id="cb46-19"><a href="chronologies.html#cb46-19"></a></span>
<span id="cb46-20"><a href="chronologies.html#cb46-20"></a><span class="co"># Création des graphiques juxtaposés</span></span>
<span id="cb46-21"><a href="chronologies.html#cb46-21"></a>facet_flags <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(natinimp <span class="op">~</span><span class="st"> </span>., <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">scales=</span><span class="st">&quot;free_x&quot;</span>)</span></code></pre></div>
<p><img src="RunH_files/figure-html/ggplot2%20chrono%20exped%20ports%20facet-1.svg" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="effectifs-cumulés-croissants-échelle-logarithmique" class="section level5">
<h5><span class="header-section-number">4.3.1.3.2</span> Effectifs cumulés croissants, échelle logarithmique</h5>
<p>Un graphique logarithmique (ou plus précisément semi-logarithmique) est une représentation graphique d’une série statistique chronologique. Il est défini en abscisse par une échelle arithmétique du temps. Il est défini en ordonnée par une échelle logarithmique. L’utilisation de ce type de graphique n’impose pas de savoir calculer des logarithmes.
Les graphiques à progression semi-logarithmique ne se lisent pas comme les graphiques à progression arithmétique. Ils permettent de comparer des rythmes d’évolution sans à avoir à effectuer des calculs. La pente donne le rythme d’évolution et non la quantité. Ils permettent également de représenter des séries statistiques de très forte amplitude dans lesquelles les valeurs se situent dans un intervalle trop grand pour permettre une bonne lisibilité de la courbe. Echelle logarithmique de base 10. On débute à 1 et non 0. Chaque fois que l’on parcours une distance, on multiple le nombre 1 par un 10 au lieu d’ajouter un nombre constant. Si on poursuit on multiple 10 par 10 ce qui fait 100.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="chronologies.html#cb47-1"></a><span class="co"># Préparation des données </span></span>
<span id="cb47-2"><a href="chronologies.html#cb47-2"></a>flagsyears_ecc &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb47-3"><a href="chronologies.html#cb47-3"></a><span class="st">  </span><span class="kw">count</span>(yearam, natinimp) <span class="op">%&gt;%</span></span>
<span id="cb47-4"><a href="chronologies.html#cb47-4"></a><span class="st">  </span><span class="kw">group_by</span>(natinimp) <span class="op">%&gt;%</span></span>
<span id="cb47-5"><a href="chronologies.html#cb47-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ecc =</span> <span class="kw">cumsum</span>(n)) <span class="op">%&gt;%</span></span>
<span id="cb47-6"><a href="chronologies.html#cb47-6"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(natinimp)) <span class="op">%&gt;%</span></span>
<span id="cb47-7"><a href="chronologies.html#cb47-7"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span>natinimp <span class="op">==</span><span class="st">&quot;Other&quot;</span> <span class="op">&amp;</span><span class="st"> </span><span class="op">!</span>natinimp <span class="op">==</span><span class="st"> &quot;Portugal&quot;</span>) </span>
<span id="cb47-8"><a href="chronologies.html#cb47-8"></a></span>
<span id="cb47-9"><a href="chronologies.html#cb47-9"></a>n_exped_last &lt;-<span class="st"> </span>flagsyears_ecc <span class="op">%&gt;%</span></span>
<span id="cb47-10"><a href="chronologies.html#cb47-10"></a><span class="st">  </span><span class="kw">slice</span>(<span class="kw">which.max</span>(yearam))</span></code></pre></div>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="chronologies.html#cb48-1"></a><span class="co"># </span></span>
<span id="cb48-2"><a href="chronologies.html#cb48-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb48-3"><a href="chronologies.html#cb48-3"></a></span>
<span id="cb48-4"><a href="chronologies.html#cb48-4"></a></span>
<span id="cb48-5"><a href="chronologies.html#cb48-5"></a>log_flags &lt;-<span class="st"> </span><span class="kw">ggplot</span> (flagsyears_ecc, <span class="kw">aes</span>(<span class="dt">x=</span>yearam, <span class="dt">y=</span>ecc, <span class="dt">color=</span>natinimp)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb48-6"><a href="chronologies.html#cb48-6"></a><span class="kw">geom_line</span>() <span class="op">+</span></span>
<span id="cb48-7"><a href="chronologies.html#cb48-7"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data =</span> n_exped_last, <span class="kw">aes</span>(<span class="dt">x =</span> yearam, <span class="dt">y =</span> ecc , <span class="dt">group=</span>natinimp), <span class="dt">shape =</span> <span class="dv">21</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">size =</span> <span class="fl">1.8</span>, <span class="dt">stroke =</span> <span class="fl">1.2</span>) <span class="op">+</span></span>
<span id="cb48-8"><a href="chronologies.html#cb48-8"></a><span class="st">  </span><span class="kw">scale_y_log10</span>() <span class="op">+</span></span>
<span id="cb48-9"><a href="chronologies.html#cb48-9"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb48-10"><a href="chronologies.html#cb48-10"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Pavillons&quot;</span>,</span>
<span id="cb48-11"><a href="chronologies.html#cb48-11"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019) variable yearam&quot;</span>,</span>
<span id="cb48-12"><a href="chronologies.html#cb48-12"></a>       <span class="dt">x=</span><span class="st">&quot;&quot;</span>, <span class="dt">y=</span><span class="st">&quot;expéditions&quot;</span>) <span class="op">+</span></span>
<span id="cb48-13"><a href="chronologies.html#cb48-13"></a><span class="st">   </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb48-14"><a href="chronologies.html#cb48-14"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">linetype=</span><span class="st">&quot;solid&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb48-15"><a href="chronologies.html#cb48-15"></a><span class="st">   </span><span class="kw">scale_colour_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Dark2&quot;</span>)</span>
<span id="cb48-16"><a href="chronologies.html#cb48-16"></a>   log_flags</span></code></pre></div>
<p><img src="RunH_files/figure-html/ggplot2%20chrono%20exped%20ports%20ecc-1.svg" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="chronologie-comparative-des-expéditions-de-traite-en-fonction-des-ports-de-départs" class="section level4">
<h4><span class="header-section-number">4.3.1.4</span> Chronologie comparative des expéditions de traite en fonction des ports de départs</h4>
<div id="evolution-des-ports-entre-1774-et-1779" class="section level5">
<h5><span class="header-section-number">4.3.1.4.1</span> Evolution des ports entre 1774 et 1779</h5>
<p>La période 1774-1779 connaît une chute brutale de la traite. Les instructions ci dessous visent à décrire l’évolution des expéditions en fonction des ports.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="chronologies.html#cb49-1"></a>evolution_ports_<span class="dv">1774</span>_<span class="dv">79</span> &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb49-2"><a href="chronologies.html#cb49-2"></a><span class="st">  </span><span class="kw">filter</span>(yeardep <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1774</span> <span class="op">&amp;</span><span class="st"> </span>yeardep <span class="op">&lt;=</span><span class="st"> </span><span class="dv">1779</span>) <span class="op">%&gt;%</span></span>
<span id="cb49-3"><a href="chronologies.html#cb49-3"></a><span class="st">  </span><span class="kw">count</span>(ptdepimp, yeardep) <span class="op">%&gt;%</span></span>
<span id="cb49-4"><a href="chronologies.html#cb49-4"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> yeardep, <span class="dt">values_from =</span> n, <span class="dt">names_prefix =</span> <span class="st">&quot;annee_&quot;</span>) </span>
<span id="cb49-5"><a href="chronologies.html#cb49-5"></a>  evolution_ports_<span class="dv">1774</span>_<span class="dv">79</span></span></code></pre></div>
<pre><code>## # A tibble: 47 x 7
##    ptdepimp    annee_1774 annee_1775 annee_1776 annee_1777 annee_1778 annee_1779
##    &lt;chr&gt;            &lt;int&gt;      &lt;int&gt;      &lt;int&gt;      &lt;int&gt;      &lt;int&gt;      &lt;int&gt;
##  1 Amsterdam            1          1          1         NA         NA         NA
##  2 Antigua, p~         NA          1         NA         NA         NA         NA
##  3 Bahia, por~         22         24         21         19         29         29
##  4 Barbados, ~         NA         NA          1         NA         NA         NA
##  5 Bordeaux            13         10         10          3          2         NA
##  6 Boston               7         NA         NA         NA         NA         NA
##  7 Bristol             20         20          8          2          2         NA
##  8 British Ca~         NA         NA          3         NA          1         NA
##  9 Charleston           2         NA         NA         NA         NA         NA
## 10 Chester             NA          1         NA         NA         NA         NA
## # ... with 37 more rows</code></pre>
</div>
<div id="représentation-graphique-brute" class="section level5">
<h5><span class="header-section-number">4.3.1.4.2</span> Représentation graphique brute</h5>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="chronologies.html#cb51-1"></a>ports_depart_chrono &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb51-2"><a href="chronologies.html#cb51-2"></a><span class="st">  </span><span class="kw">count</span>(yearam, ptdepimp) <span class="op">%&gt;%</span></span>
<span id="cb51-3"><a href="chronologies.html#cb51-3"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(ptdepimp)) </span></code></pre></div>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="chronologies.html#cb52-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb52-2"><a href="chronologies.html#cb52-2"></a><span class="co"># Création d&#39;un graphique en bâtons</span></span>
<span id="cb52-3"><a href="chronologies.html#cb52-3"></a>plot_ports_depart_chrono &lt;-<span class="st"> </span><span class="kw">ggplot</span>(ports_depart_chrono, <span class="kw">aes</span>(<span class="dt">x=</span>yearam, <span class="dt">y=</span>n, <span class="dt">group=</span>ptdepimp)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb52-4"><a href="chronologies.html#cb52-4"></a><span class="kw">geom_line</span>() </span>
<span id="cb52-5"><a href="chronologies.html#cb52-5"></a></span>
<span id="cb52-6"><a href="chronologies.html#cb52-6"></a>plot_ports_depart_chrono</span></code></pre></div>
<p><img src="RunH_files/figure-html/plot%20exp%20ports%20ggplot2-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="représentation-graphique-partitionnée-des-neuf-principaux-ports-effectifs" class="section level5">
<h5><span class="header-section-number">4.3.1.4.3</span> Représentation graphique partitionnée des neuf principaux ports (effectifs)</h5>
<p>Le graphique brut est illisible. Vous pouvez envisagez un représentation graphique alternative en mettant en évidence les ports les plus actifs en combinant la fonction <code>gghighlight</code> (package gghighlight) et la fonction <code>facet_wrap</code> (package ggplot2). Lors de la préparation des données , vous devez créer deux tableaux de données et les réunir par une jointure.</p>
<ul>
<li>Le tableau <code>ports_depart_chrono_total</code> compte le total des expéditions par port pour en afficher le rang (nouvelle colonne <code>rank</code>, fonction <code>dense_rank</code>).</li>
<li>Le tableau <code>ports_depart_chrono_annees</code> compte le nombre d’expéditions par port et part années.</li>
</ul>
<p>Le tableau final <code>ports_chrono_rank</code> combine les 2 tableaux. Il vous reste à mettre en évidence dans ggplot2 les courbes des principaux ports en se basant sur les valeurs de la colonne <code>rank</code>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="chronologies.html#cb53-1"></a>ports_depart_chrono_total &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb53-2"><a href="chronologies.html#cb53-2"></a><span class="st">  </span><span class="kw">count</span>(ptdepimp) <span class="op">%&gt;%</span></span>
<span id="cb53-3"><a href="chronologies.html#cb53-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rank =</span> <span class="kw">dense_rank</span>(<span class="kw">desc</span>(n))) </span>
<span id="cb53-4"><a href="chronologies.html#cb53-4"></a></span>
<span id="cb53-5"><a href="chronologies.html#cb53-5"></a>ports_depart_chrono_annees &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb53-6"><a href="chronologies.html#cb53-6"></a><span class="st">  </span><span class="kw">count</span>(yearam, ptdepimp) <span class="op">%&gt;%</span></span>
<span id="cb53-7"><a href="chronologies.html#cb53-7"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(ptdepimp))</span>
<span id="cb53-8"><a href="chronologies.html#cb53-8"></a></span>
<span id="cb53-9"><a href="chronologies.html#cb53-9"></a>ports_chrono_rank &lt;-<span class="st"> </span><span class="kw">left_join</span>(ports_depart_chrono_annees, ports_depart_chrono_total,</span>
<span id="cb53-10"><a href="chronologies.html#cb53-10"></a>                               <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;ptdepimp&quot;</span> =<span class="st"> &quot;ptdepimp&quot;</span>))</span>
<span id="cb53-11"><a href="chronologies.html#cb53-11"></a></span>
<span id="cb53-12"><a href="chronologies.html#cb53-12"></a>ports_chrono_rank &lt;-<span class="st"> </span>ports_chrono_rank <span class="op">%&gt;%</span></span>
<span id="cb53-13"><a href="chronologies.html#cb53-13"></a><span class="st">  </span><span class="kw">rename</span>(<span class="dt">n =</span>n.x ) <span class="op">%&gt;%</span></span>
<span id="cb53-14"><a href="chronologies.html#cb53-14"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>n.y)</span>
<span id="cb53-15"><a href="chronologies.html#cb53-15"></a></span>
<span id="cb53-16"><a href="chronologies.html#cb53-16"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb53-17"><a href="chronologies.html#cb53-17"></a><span class="kw">library</span>(gghighlight)</span>
<span id="cb53-18"><a href="chronologies.html#cb53-18"></a></span>
<span id="cb53-19"><a href="chronologies.html#cb53-19"></a>plot_ports_depart_chrono2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(ports_chrono_rank, <span class="kw">aes</span>(<span class="dt">x=</span>yearam, <span class="dt">y=</span>n, <span class="dt">group=</span>ptdepimp)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb53-20"><a href="chronologies.html#cb53-20"></a><span class="kw">geom_step</span>(<span class="kw">aes</span>(<span class="dt">x=</span>yearam, <span class="dt">y=</span>n, <span class="dt">group=</span>ptdepimp) , <span class="dt">color=</span><span class="st">&quot;#d95f02&quot;</span> , <span class="dt">show.legend=</span><span class="ot">FALSE</span>, <span class="dt">size =</span> <span class="fl">0.5</span>) <span class="op">+</span></span>
<span id="cb53-21"><a href="chronologies.html#cb53-21"></a><span class="st">  </span><span class="kw">gghighlight</span>(<span class="kw">max</span>(rank) <span class="op">&lt;</span><span class="st"> </span><span class="dv">11</span>, <span class="dt">use_direct_label =</span> <span class="ot">FALSE</span>,</span>
<span id="cb53-22"><a href="chronologies.html#cb53-22"></a>              <span class="dt">unhighlighted_params =</span> <span class="kw">list</span>(<span class="dt">size =</span> <span class="fl">0.25</span>, <span class="dt">colour =</span> <span class="kw">alpha</span>(<span class="st">&quot;grey85&quot;</span>, <span class="fl">0.4</span>))) <span class="op">+</span></span>
<span id="cb53-23"><a href="chronologies.html#cb53-23"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">1500</span>, <span class="dv">1875</span>, <span class="dt">by=</span><span class="dv">100</span>)) <span class="op">+</span></span>
<span id="cb53-24"><a href="chronologies.html#cb53-24"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb53-25"><a href="chronologies.html#cb53-25"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Principaux ports de départ&quot;</span>,</span>
<span id="cb53-26"><a href="chronologies.html#cb53-26"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019) variable yearam&quot;</span>,</span>
<span id="cb53-27"><a href="chronologies.html#cb53-27"></a>       <span class="dt">x =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb53-28"><a href="chronologies.html#cb53-28"></a>       <span class="dt">y =</span><span class="st">&quot;expéditions&quot;</span>) <span class="op">+</span></span>
<span id="cb53-29"><a href="chronologies.html#cb53-29"></a><span class="st">  </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb53-30"><a href="chronologies.html#cb53-30"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>ptdepimp, <span class="dt">scales=</span><span class="st">&quot;free_x&quot;</span>)</span>
<span id="cb53-31"><a href="chronologies.html#cb53-31"></a></span>
<span id="cb53-32"><a href="chronologies.html#cb53-32"></a>plot_ports_depart_chrono2</span></code></pre></div>
<p><img src="RunH_files/figure-html/plot%20exp%20ports%20ggplot2_2-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="représentation-graphique-partitionnée-des-neuf-principaux-ports-effectifs-cumulés-croissants" class="section level5">
<h5><span class="header-section-number">4.3.1.4.4</span> Représentation graphique partitionnée des neuf principaux ports (effectifs cumulés croissants)</h5>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="chronologies.html#cb54-1"></a>ports_depart_chrono_total &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb54-2"><a href="chronologies.html#cb54-2"></a><span class="st">  </span><span class="kw">count</span>(ptdepimp) <span class="op">%&gt;%</span></span>
<span id="cb54-3"><a href="chronologies.html#cb54-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rank =</span> <span class="kw">dense_rank</span>(<span class="kw">desc</span>(n))) </span>
<span id="cb54-4"><a href="chronologies.html#cb54-4"></a></span>
<span id="cb54-5"><a href="chronologies.html#cb54-5"></a>ports_depart_chrono_annees &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb54-6"><a href="chronologies.html#cb54-6"></a><span class="st">  </span><span class="kw">count</span>(yearam, ptdepimp) <span class="op">%&gt;%</span></span>
<span id="cb54-7"><a href="chronologies.html#cb54-7"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(ptdepimp))</span>
<span id="cb54-8"><a href="chronologies.html#cb54-8"></a></span>
<span id="cb54-9"><a href="chronologies.html#cb54-9"></a>ports_chrono_rank &lt;-<span class="st"> </span><span class="kw">left_join</span>(ports_depart_chrono_annees, ports_depart_chrono_total,</span>
<span id="cb54-10"><a href="chronologies.html#cb54-10"></a>                               <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;ptdepimp&quot;</span> =<span class="st"> &quot;ptdepimp&quot;</span>))</span>
<span id="cb54-11"><a href="chronologies.html#cb54-11"></a></span>
<span id="cb54-12"><a href="chronologies.html#cb54-12"></a>ports_chrono_rank_ecc &lt;-<span class="st"> </span>ports_chrono_rank <span class="op">%&gt;%</span></span>
<span id="cb54-13"><a href="chronologies.html#cb54-13"></a><span class="st">  </span><span class="kw">rename</span>(<span class="dt">n =</span>n.x ) <span class="op">%&gt;%</span></span>
<span id="cb54-14"><a href="chronologies.html#cb54-14"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>n.y) <span class="op">%&gt;%</span></span>
<span id="cb54-15"><a href="chronologies.html#cb54-15"></a><span class="st">  </span><span class="kw">group_by</span>(ptdepimp) <span class="op">%&gt;%</span></span>
<span id="cb54-16"><a href="chronologies.html#cb54-16"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ecc =</span> <span class="kw">cumsum</span>(n)) <span class="op">%&gt;%</span></span>
<span id="cb54-17"><a href="chronologies.html#cb54-17"></a><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span></span>
<span id="cb54-18"><a href="chronologies.html#cb54-18"></a><span class="st">  </span><span class="kw">arrange</span>(ptdepimp, yearam)</span>
<span id="cb54-19"><a href="chronologies.html#cb54-19"></a></span>
<span id="cb54-20"><a href="chronologies.html#cb54-20"></a></span>
<span id="cb54-21"><a href="chronologies.html#cb54-21"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb54-22"><a href="chronologies.html#cb54-22"></a><span class="kw">library</span>(gghighlight)</span>
<span id="cb54-23"><a href="chronologies.html#cb54-23"></a></span>
<span id="cb54-24"><a href="chronologies.html#cb54-24"></a>plot_ports_depart_chrono_ecc &lt;-<span class="st"> </span><span class="kw">ggplot</span>(ports_chrono_rank_ecc, <span class="kw">aes</span>(<span class="dt">x=</span>yearam, <span class="dt">y=</span>ecc, <span class="dt">group=</span>ptdepimp)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb54-25"><a href="chronologies.html#cb54-25"></a><span class="kw">geom_step</span>(<span class="kw">aes</span>(<span class="dt">x=</span>yearam, <span class="dt">y=</span>ecc, <span class="dt">group=</span>ptdepimp), <span class="dt">color=</span><span class="st">&quot;#d95f02&quot;</span> , <span class="dt">show.legend=</span><span class="ot">FALSE</span>, <span class="dt">size =</span> <span class="fl">0.5</span>) <span class="op">+</span></span>
<span id="cb54-26"><a href="chronologies.html#cb54-26"></a><span class="st">  </span><span class="kw">gghighlight</span>(<span class="kw">max</span>(rank) <span class="op">&lt;</span><span class="st"> </span><span class="dv">11</span>, <span class="dt">use_direct_label =</span> <span class="ot">FALSE</span>,</span>
<span id="cb54-27"><a href="chronologies.html#cb54-27"></a>              <span class="dt">unhighlighted_params =</span> <span class="kw">list</span>(<span class="dt">size =</span> <span class="fl">0.25</span>, <span class="dt">colour =</span> <span class="kw">alpha</span>(<span class="st">&quot;grey85&quot;</span>, <span class="fl">0.4</span>))) <span class="op">+</span></span>
<span id="cb54-28"><a href="chronologies.html#cb54-28"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dv">1500</span>, <span class="dv">1875</span>, <span class="dt">by=</span><span class="dv">100</span>)) <span class="op">+</span></span>
<span id="cb54-29"><a href="chronologies.html#cb54-29"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite atlantique&quot;</span>,</span>
<span id="cb54-30"><a href="chronologies.html#cb54-30"></a>       <span class="dt">subtitle =</span><span class="st">&quot;Principaux ports de départ, effectifs cumulés croissants&quot;</span>,</span>
<span id="cb54-31"><a href="chronologies.html#cb54-31"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019) variable yearam&quot;</span>,</span>
<span id="cb54-32"><a href="chronologies.html#cb54-32"></a>       <span class="dt">x =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb54-33"><a href="chronologies.html#cb54-33"></a>       <span class="dt">y =</span><span class="st">&quot;expéd.&quot;</span>) <span class="op">+</span></span>
<span id="cb54-34"><a href="chronologies.html#cb54-34"></a><span class="st">  </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb54-35"><a href="chronologies.html#cb54-35"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>ptdepimp, <span class="dt">scales=</span><span class="st">&quot;free_x&quot;</span>)</span>
<span id="cb54-36"><a href="chronologies.html#cb54-36"></a></span>
<span id="cb54-37"><a href="chronologies.html#cb54-37"></a>plot_ports_depart_chrono_ecc</span></code></pre></div>
<p><img src="RunH_files/figure-html/princp_ports_ecc-1.svg" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="chronologie-darrivée-des-navires-principaux-lieux-dachat-desclaves" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Chronologie d’arrivée des navires, principaux lieux d’achat d’esclaves</h3>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="chronologies.html#cb55-1"></a>lieux_achats &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb55-2"><a href="chronologies.html#cb55-2"></a><span class="st">  </span><span class="kw">select</span>(mjbyptimp, datebuy) <span class="op">%&gt;%</span></span>
<span id="cb55-3"><a href="chronologies.html#cb55-3"></a><span class="st">  </span><span class="kw">arrange</span>(datebuy) <span class="op">%&gt;%</span></span>
<span id="cb55-4"><a href="chronologies.html#cb55-4"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(datebuy))</span></code></pre></div>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="chronologies.html#cb56-1"></a>gg_chrono2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(lieux_achats, <span class="kw">aes</span>(<span class="dt">x=</span> datebuy, <span class="dt">y=</span> mjbyptimp))</span>
<span id="cb56-2"><a href="chronologies.html#cb56-2"></a>gg_chrono2 <span class="op">+</span></span>
<span id="cb56-3"><a href="chronologies.html#cb56-3"></a><span class="st">  </span><span class="kw">geom_point</span> (<span class="dt">color=</span><span class="st">&quot;#d95f02&quot;</span>, <span class="dt">alpha =</span><span class="fl">0.3</span>, <span class="dt">size =</span> <span class="fl">1.5</span>, <span class="dt">position =</span> <span class="kw">position_jitter</span>(<span class="dt">width =</span> <span class="dv">0</span>, <span class="dt">height =</span> <span class="fl">0.25</span>)) <span class="op">+</span></span>
<span id="cb56-4"><a href="chronologies.html#cb56-4"></a><span class="st">  </span><span class="kw">scale_x_date</span>(<span class="dt">date_breaks =</span> <span class="st">&quot;10 year&quot;</span>, <span class="dt">date_minor_breaks =</span> <span class="st">&quot;5 year&quot;</span>,</span>
<span id="cb56-5"><a href="chronologies.html#cb56-5"></a>             <span class="dt">date_labels =</span> <span class="st">&quot;%Y&quot;</span>) <span class="op">+</span></span>
<span id="cb56-6"><a href="chronologies.html#cb56-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Principaux lieux d&#39;achat d&#39;esclaves&quot;</span>,<span class="dt">subtitle =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb56-7"><a href="chronologies.html#cb56-7"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019) variables mjbyptimp et datebuy&quot;</span>,</span>
<span id="cb56-8"><a href="chronologies.html#cb56-8"></a>       <span class="dt">x=</span><span class="st">&quot;&quot;</span>, <span class="dt">y=</span><span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb56-9"><a href="chronologies.html#cb56-9"></a><span class="st">  </span><span class="kw">theme_minimal</span>() </span></code></pre></div>
<p><img src="RunH_files/figure-html/chrono%20lieux%20achats%20ggplot22-1.svg" width="1152" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="exemples-1" class="section level2">
<h2><span class="header-section-number">4.4</span> Exemples</h2>
<div id="chronologie-des-expéditions-de-traite-à-destination-de-saint-domingue" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Chronologie des expéditions de traite à destination de Saint-Domingue</h3>
<div id="tableau-deffectifs-1" class="section level4">
<h4><span class="header-section-number">4.4.1.1</span> Tableau d’effectifs</h4>
<p>Vous devez filtrer les expéditions en vous fondant sur la variable <code>mjselimp</code> (<em>Imputed principal region of slave disembarkation</em>) puis compter le nombre d’expéditions par années d’arrivée en Amérique (variable <code>yearam</code>) avec la fonction <code>count</code>.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="chronologies.html#cb57-1"></a>stdoming1 &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb57-2"><a href="chronologies.html#cb57-2"></a><span class="st">  </span><span class="kw">filter</span>(mjselimp <span class="op">==</span><span class="st">&quot;Saint-Domingue&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb57-3"><a href="chronologies.html#cb57-3"></a><span class="st">  </span><span class="kw">count</span>(yearam) </span>
<span id="cb57-4"><a href="chronologies.html#cb57-4"></a></span>
<span id="cb57-5"><a href="chronologies.html#cb57-5"></a><span class="kw">print</span>(stdoming1)</span></code></pre></div>
<pre><code>## # A tibble: 96 x 2
##    yearam     n
##     &lt;dbl&gt; &lt;int&gt;
##  1   1679     2
##  2   1684     1
##  3   1685     4
##  4   1686     3
##  5   1687     1
##  6   1693     1
##  7   1699     2
##  8   1701     2
##  9   1708     1
## 10   1709     1
## # ... with 86 more rows</code></pre>
</div>
<div id="représentation-graphique" class="section level4">
<h4><span class="header-section-number">4.4.1.2</span> Représentation graphique</h4>
<p>Le diagramme en ligne est conçu avec la fonction <code>plot</code> en base R. Elle prend, comme premier argument le tableau de données à visualiser et, comme second argument le type de représentation (ici <code>l</code>pour <em>line</em>). Les arguments qui suivent permettent d’habiller le graphique.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="chronologies.html#cb59-1"></a>  <span class="kw">plot</span>(stdoming1,</span>
<span id="cb59-2"><a href="chronologies.html#cb59-2"></a>       <span class="dt">type=</span><span class="st">&quot;l&quot;</span>,                                                         </span>
<span id="cb59-3"><a href="chronologies.html#cb59-3"></a>      <span class="dt">main=</span><span class="st">&quot;Chronologie des expéditions de traite atlantique à destination de Saint Domingue&quot;</span>,</span>
<span id="cb59-4"><a href="chronologies.html#cb59-4"></a>      <span class="dt">sub=</span><span class="st">&quot;Voyages, The TransAtlantic Salve Trade Db (2019)&quot;</span>,</span>
<span id="cb59-5"><a href="chronologies.html#cb59-5"></a>      <span class="dt">xlab=</span><span class="st">&quot;années&quot;</span>,</span>
<span id="cb59-6"><a href="chronologies.html#cb59-6"></a>      <span class="dt">ylab=</span><span class="st">&quot;expéditions&quot;</span>,</span>
<span id="cb59-7"><a href="chronologies.html#cb59-7"></a>      <span class="dt">cex.main=</span><span class="fl">0.9</span>,</span>
<span id="cb59-8"><a href="chronologies.html#cb59-8"></a>      <span class="dt">cex.sub=</span><span class="fl">0.7</span>,</span>
<span id="cb59-9"><a href="chronologies.html#cb59-9"></a>      <span class="dt">cex.lab=</span><span class="fl">0.75</span>)</span></code></pre></div>
<p><img src="RunH_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
</div>
<div id="nombre-desclaves-embarqués-par-années-à-destination-de-saint-domingue" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Nombre d’esclaves embarqués par années à destination de Saint-Domingue</h3>
<div id="tableau" class="section level4">
<h4><span class="header-section-number">4.4.2.1</span> Tableau</h4>
<p>Excluez en premier les expéditions dont le nombre d’esclaves embarqués (variable <code>slaximp</code> ) est inconnu par l’utilisation conjointe des fonctions <code>filter</code>et <code>complete.cases</code>. Regroupez ensuite les années d’arrivée en Amérique en appliquant la fonction <code>group_by</code> à la variable <code>yearam</code> afin de pouvoir résumer les données (<code>summarise</code>) par la somme (<code>sum</code>) des esclaves embarqués.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="chronologies.html#cb60-1"></a>stdoming2 &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb60-2"><a href="chronologies.html#cb60-2"></a><span class="st">  </span><span class="kw">filter</span>(mjselimp <span class="op">==</span><span class="st">&quot;Saint-Domingue&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb60-3"><a href="chronologies.html#cb60-3"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(slaximp)) <span class="op">%&gt;%</span><span class="st">           </span></span>
<span id="cb60-4"><a href="chronologies.html#cb60-4"></a><span class="st">  </span><span class="kw">group_by</span>(yearam) <span class="op">%&gt;%</span></span>
<span id="cb60-5"><a href="chronologies.html#cb60-5"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n_esc =</span> <span class="kw">sum</span>(slaximp))</span>
<span id="cb60-6"><a href="chronologies.html#cb60-6"></a><span class="kw">print</span>(stdoming2)</span></code></pre></div>
<pre><code>## # A tibble: 96 x 2
##    yearam n_esc
##     &lt;dbl&gt; &lt;dbl&gt;
##  1   1679   436
##  2   1684   380
##  3   1685  1092
##  4   1686   504
##  5   1687   316
##  6   1693   524
##  7   1699   781
##  8   1701   607
##  9   1708   316
## 10   1709   592
## # ... with 86 more rows</code></pre>
</div>
<div id="représentation-graphique-1" class="section level4">
<h4><span class="header-section-number">4.4.2.2</span> Représentation graphique</h4>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="chronologies.html#cb62-1"></a>  <span class="kw">plot</span>(stdoming2,</span>
<span id="cb62-2"><a href="chronologies.html#cb62-2"></a>       <span class="dt">type=</span><span class="st">&quot;l&quot;</span>,                                                         </span>
<span id="cb62-3"><a href="chronologies.html#cb62-3"></a>      <span class="dt">main=</span><span class="st">&quot;Chronologie du nombre d&#39;esclaves embarqués à destination de Saint Domingue&quot;</span>,</span>
<span id="cb62-4"><a href="chronologies.html#cb62-4"></a>      <span class="dt">sub=</span><span class="st">&quot;Voyages, The TransAtlantic Salve Trade Db (2019)&quot;</span>,</span>
<span id="cb62-5"><a href="chronologies.html#cb62-5"></a>      <span class="dt">xlab=</span><span class="st">&quot;années&quot;</span>,</span>
<span id="cb62-6"><a href="chronologies.html#cb62-6"></a>      <span class="dt">ylab=</span><span class="st">&quot;expéditions&quot;</span>,</span>
<span id="cb62-7"><a href="chronologies.html#cb62-7"></a>      <span class="dt">cex.main=</span><span class="fl">0.9</span>,</span>
<span id="cb62-8"><a href="chronologies.html#cb62-8"></a>      <span class="dt">cex.sub=</span><span class="fl">0.7</span>,</span>
<span id="cb62-9"><a href="chronologies.html#cb62-9"></a>      <span class="dt">cex.lab=</span><span class="fl">0.75</span>)</span></code></pre></div>
<p><img src="RunH_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
</div>
</div>
<div id="chronologie-décennale-des-expéditions-de-traite-à-destination-de-saint-domingue-selon-les-ports-de-départ" class="section level3">
<h3><span class="header-section-number">4.4.3</span> Chronologie décennale des expéditions de traite à destination de Saint-Domingue selon les ports de départ</h3>
<p>Filtrez les expéditions en vous fondant sur la variable <code>mjselimp</code> (<em>Imputed principal region of slave disembarkation</em>) puis compter le nombre d’expéditions par ports de départs (<code>ptdepimp</code>) et par décennies (variable <code>year10</code>) avec la fonction <code>count</code>.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="chronologies.html#cb63-1"></a>stdoming_y10A &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb63-2"><a href="chronologies.html#cb63-2"></a><span class="st">  </span><span class="kw">filter</span>(mjselimp <span class="op">==</span><span class="st">&quot;Saint-Domingue&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb63-3"><a href="chronologies.html#cb63-3"></a><span class="st">  </span><span class="kw">count</span>(year10, ptdepimp)</span>
<span id="cb63-4"><a href="chronologies.html#cb63-4"></a><span class="kw">print</span>(stdoming_y10A )</span></code></pre></div>
<pre><code>## # A tibble: 134 x 3
##    year10          ptdepimp                     n
##    &lt;chr&gt;           &lt;chr&gt;                    &lt;int&gt;
##  1 years 1671-1680 France, port unspecified     1
##  2 years 1671-1680 Saint-Malo                   1
##  3 years 1681-90   Bordeaux                     1
##  4 years 1681-90   Dunkerque                    1
##  5 years 1681-90   Honfleur                     1
##  6 years 1681-90   La Rochelle                  2
##  7 years 1681-90   Le Havre                     3
##  8 years 1681-90   Saint-Malo                   1
##  9 years 1691-1700 Saint-Malo                   1
## 10 years 1691-1700 &lt;NA&gt;                         2
## # ... with 124 more rows</code></pre>
<div id="diagramme-en-barres-empilées" class="section level5">
<h5><span class="header-section-number">4.4.3.0.1</span> Diagramme en barres empilées</h5>
<p>Un diagramme à barres empilées permet de visualiser le nombre total des expéditions à destination de Saint-Domingue par décennies et ports de départ des navires.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="chronologies.html#cb65-1"></a>voyages <span class="op">%&gt;%</span></span>
<span id="cb65-2"><a href="chronologies.html#cb65-2"></a><span class="st">  </span><span class="kw">filter</span>(mjselimp <span class="op">==</span><span class="st">&quot;Saint-Domingue&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb65-3"><a href="chronologies.html#cb65-3"></a><span class="st">  </span><span class="kw">distinct</span>(ptdepimp)</span></code></pre></div>
<pre><code>## # A tibble: 38 x 1
##    ptdepimp                   
##    &lt;chr&gt;                      
##  1 &lt;NA&gt;                       
##  2 Nantes                     
##  3 Vlissingen                 
##  4 Hellevoetsluis             
##  5 Bristol                    
##  6 St. Kitts, port unspecified
##  7 Boston                     
##  8 St. Thomas                 
##  9 Bayonne                    
## 10 Bordeaux                   
## # ... with 28 more rows</code></pre>
<p>38 ports ont pratiqué la traite à destination de Saint-Domingue. Afin d’envisager un diagramme en barres empilées lisible vous devez regrouper les ports dont l’activité est la moins importante sous le dénominatif “autres”. Pour ce faire, les fonctions <code>mutate</code> et <code>replace</code> sont utilisées pour recoder les noms de ports en fonction d’une condition. Ainsi, tous les ports dont le nombre d’expéditions est inférieur à 50 par décennies <code>n &lt; 50</code> sont renommés en <code>Autres (exped. &lt; 20)</code> permettant de passer de 38 à 5 valeurs différentes.
Enfin le texte <code>years</code> préfixant les décennies est supprimé ou plus exactement remplacé par une chaîne de caractères vide (fonction <code>sub</code>associée à <code>mutate</code>).</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="chronologies.html#cb67-1"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb67-2"><a href="chronologies.html#cb67-2"></a>stdoming_y10B &lt;-<span class="st"> </span>voyages <span class="op">%&gt;%</span></span>
<span id="cb67-3"><a href="chronologies.html#cb67-3"></a><span class="st">  </span><span class="kw">filter</span>(mjselimp <span class="op">==</span><span class="st">&quot;Saint-Domingue&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb67-4"><a href="chronologies.html#cb67-4"></a><span class="st">  </span><span class="kw">count</span>(year10, ptdepimp) <span class="op">%&gt;%</span></span>
<span id="cb67-5"><a href="chronologies.html#cb67-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ptdepimp =</span> <span class="kw">replace</span>(ptdepimp, n <span class="op">&lt;</span><span class="st"> </span><span class="dv">50</span>, <span class="st">&quot;Autres (exped. &lt; 50)&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb67-6"><a href="chronologies.html#cb67-6"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year10 =</span> <span class="kw">sub</span>(<span class="st">&quot;years&quot;</span>, <span class="st">&quot;&quot;</span>, year10))</span>
<span id="cb67-7"><a href="chronologies.html#cb67-7"></a></span>
<span id="cb67-8"><a href="chronologies.html#cb67-8"></a>stdoming_y10B</span></code></pre></div>
<pre><code>## # A tibble: 134 x 3
##    year10       ptdepimp                 n
##    &lt;chr&gt;        &lt;chr&gt;                &lt;int&gt;
##  1 &quot; 1671-1680&quot; Autres (exped. &lt; 50)     1
##  2 &quot; 1671-1680&quot; Autres (exped. &lt; 50)     1
##  3 &quot; 1681-90&quot;   Autres (exped. &lt; 50)     1
##  4 &quot; 1681-90&quot;   Autres (exped. &lt; 50)     1
##  5 &quot; 1681-90&quot;   Autres (exped. &lt; 50)     1
##  6 &quot; 1681-90&quot;   Autres (exped. &lt; 50)     2
##  7 &quot; 1681-90&quot;   Autres (exped. &lt; 50)     3
##  8 &quot; 1681-90&quot;   Autres (exped. &lt; 50)     1
##  9 &quot; 1691-1700&quot; Autres (exped. &lt; 50)     1
## 10 &quot; 1691-1700&quot; Autres (exped. &lt; 50)     2
## # ... with 124 more rows</code></pre>
<p>Le diagramme empilé est réalisé avec le package ggplot2</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="chronologies.html#cb69-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> stdoming_y10B, <span class="kw">aes</span>(<span class="dt">y =</span> n, <span class="dt">x =</span> year10, <span class="dt">fill =</span> ptdepimp)) <span class="op">+</span></span>
<span id="cb69-2"><a href="chronologies.html#cb69-2"></a><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>,</span>
<span id="cb69-3"><a href="chronologies.html#cb69-3"></a>           <span class="dt">width =</span> <span class="fl">0.5</span>) <span class="op">+</span></span>
<span id="cb69-4"><a href="chronologies.html#cb69-4"></a><span class="st">  </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Dark2&quot;</span>) <span class="op">+</span></span>
<span id="cb69-5"><a href="chronologies.html#cb69-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Chronologie des expéditions de traite à destination de Saint-Domingue&quot;</span>,</span>
<span id="cb69-6"><a href="chronologies.html#cb69-6"></a>       <span class="dt">subtitle =</span><span class="st">&quot;Principaux ports de départ&quot;</span>,</span>
<span id="cb69-7"><a href="chronologies.html#cb69-7"></a>       <span class="dt">caption =</span><span class="st">&quot;Source : The Trans-Atlantic Slave Trade Database (2019) variables year10 et slaximp</span></span>
<span id="cb69-8"><a href="chronologies.html#cb69-8"></a><span class="st">       </span><span class="ch">\n</span><span class="st"> W. Cariou (2020)&quot;</span>,</span>
<span id="cb69-9"><a href="chronologies.html#cb69-9"></a>       <span class="dt">x =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb69-10"><a href="chronologies.html#cb69-10"></a>       <span class="dt">y =</span><span class="st">&quot;&quot;</span>,</span>
<span id="cb69-11"><a href="chronologies.html#cb69-11"></a>       <span class="dt">fill =</span> <span class="st">&quot;Ports de départ&quot;</span>) <span class="op">+</span></span>
<span id="cb69-12"><a href="chronologies.html#cb69-12"></a><span class="st">     </span><span class="kw">my_theme_chrono1</span>() <span class="op">+</span></span>
<span id="cb69-13"><a href="chronologies.html#cb69-13"></a><span class="st">     </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">vjust=</span> <span class="fl">0.2</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<p><img src="RunH_files/figure-html/stdoming-ptsdep-bar-1.svg" width="672" style="display: block; margin: auto;" /></p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="manipulations.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cartographie.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["RunH.pdf", "RunH.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
